(function(){
'use strict';
const app={db:null,invite:'',access:'',preview:null,state:null,products:[],index:[],selected:'',photo:'',scanner:null,poll:null,polling:false,pollTicks:0,operating:false,claiming:false,modalResolve:null};
const $=id=>document.getElementById(id), clean=v=>String(v==null?'':v).trim();
const escHtml=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=m=>m==='reposicion'?'Reposición':m==='recepcion'?'Control de remitos':'Inventario';
const num=v=>Math.max(0,Number(v)||0);
function setHidden(id,hidden){const el=$(id);if(el)el.hidden=hidden;}
function finishBoot(){const boot=$('guest-boot');boot?.classList.add('hidden');setTimeout(()=>{if(boot)boot.hidden=true;},190);}
function boot(text){if($('guest-boot-text'))$('guest-boot-text').textContent=text;}
function showError(message,title='Este acceso no está disponible'){clearInterval(app.poll);setHidden('guest-entry',true);setHidden('guest-workspace',true);setHidden('guest-error-screen',false);$('guest-error-title').textContent=title;$('guest-error-message').textContent=message||'Pedile a la persona responsable un nuevo enlace.';finishBoot();}
let toastTimer;function toast(message,type=''){const el=$('guest-toast');if(!el)return;clearTimeout(toastTimer);el.textContent=message;el.className=`guest-toast show ${type}`;toastTimer=setTimeout(()=>el.className='guest-toast',2800);}
function deviceId(){const key='sucan_guest_device';try{let value=localStorage.getItem(key);if(!value){value=crypto.randomUUID?.()||`guest-${Date.now()}-${Math.random().toString(36).slice(2)}`;localStorage.setItem(key,value);}return value;}catch(_){return`guest-${Date.now()}-${Math.random().toString(36).slice(2)}`;}}
function accessKey(){return `sucan_guest_access_${app.invite.slice(0,18)}`;}
function photoKey(){return `sucan_guest_photo_${app.invite.slice(0,18)}`;}
async function rpc(name,params){const{data,error}=await app.db.rpc(name,params);if(error)throw error;return data;}
function validPhoto(v){return /^data:image\/(?:jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(clean(v));}

async function initialize(){
  app.invite=decodeURIComponent(location.hash.slice(1));
  history.replaceState(null,'',location.pathname+location.search+location.hash);
  if(app.invite.length<24){showError('El enlace está incompleto. Escaneá nuevamente el código QR.');return;}
  const config=window.SUCANEITOR_CLOUD_CONFIG;
  if(!config?.supabaseUrl||!config?.supabaseKey||!window.supabase){showError('No se pudo conectar con Sucaneitor.');return;}
  app.db=window.supabase.createClient(config.supabaseUrl,config.supabaseKey,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
  try{
    const [preview,products]=await Promise.all([rpc('op_invitacion_preview',{p_token:app.invite}),fetch('/products.json',{cache:'no-store'}).then(r=>r.ok?r.json():[]).catch(()=>[])]);
    if(!preview?.ok){showError(preview?.error);return;}
    app.preview=preview;app.products=Array.isArray(products)?products:[];app.index=window.SucaneitorSearch?.createSearchIndex(app.products)||[];
    const remembered=localStorage.getItem(accessKey());
    if(remembered){app.access=remembered;app.photo=localStorage.getItem(photoKey())||'';const joined=await loadState(false);if(joined){startWorkspace();return;}localStorage.removeItem(accessKey());localStorage.removeItem(photoKey());app.access='';}
    showEntry();
  }catch(error){showError(error.message||'No se pudo verificar la invitación.');}
}
function showEntry(){const session=app.preview.session||{};$('guest-module-label').textContent=`${label(session.module).toUpperCase()} COMPARTIDO`;$('guest-session-name').textContent=session.name||label(session.module);$('guest-session-route').textContent=session.route||session.location||'';setHidden('guest-entry',false);finishBoot();}

async function compressPhoto(file){
  if(!file||!file.type.startsWith('image/'))throw new Error('Seleccioná una fotografía válida.');
  const url=URL.createObjectURL(file);try{const image=await new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('No se pudo abrir la foto.'));img.src=url;});const size=360,scale=Math.min(1,size/Math.max(image.naturalWidth,image.naturalHeight)),w=Math.max(1,Math.round(image.naturalWidth*scale)),h=Math.max(1,Math.round(image.naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d',{alpha:false}).drawImage(image,0,0,w,h);let quality=.78,result=canvas.toDataURL('image/jpeg',quality);while(result.length>340000&&quality>.35){quality-=.1;result=canvas.toDataURL('image/jpeg',quality);}if(result.length>350000)throw new Error('La foto es demasiado grande. Intentá nuevamente.');return result;}finally{URL.revokeObjectURL(url);}
}
async function onPhoto(event){const error=$('guest-join-error');error.textContent='';try{app.photo=await compressPhoto(event.target.files?.[0]);$('guest-photo-preview').innerHTML=`<img src="${app.photo}" alt="Tu foto">`;$('guest-photo-title').textContent='Cambiar foto';}catch(e){app.photo='';error.textContent=e.message;}}
async function join(event){event.preventDefault();const name=clean($('guest-name').value),error=$('guest-join-error'),button=$('guest-join-button');error.textContent='';if(name.length<2){error.textContent='Ingresá tu nombre.';return;}if(!validPhoto(app.photo)){error.textContent='Tomate una foto para poder ingresar.';return;}button.disabled=true;button.textContent='Ingresando…';try{const data=await rpc('op_invitacion_unirse',{p_token:app.invite,p_nombre:name,p_foto:app.photo,p_dispositivo:deviceId()});app.access=data.access_token;localStorage.setItem(accessKey(),app.access);localStorage.setItem(photoKey(),app.photo);await loadState(true);startWorkspace();}catch(e){error.textContent=e.message||'No se pudo ingresar.';}finally{button.disabled=false;button.textContent='Ingresar a colaborar';}}

function mergeRows(previous,next){const map=new Map((previous||[]).map(row=>[clean(row.code),row]));(next||[]).forEach(row=>map.set(clean(row.code),row));return[...map.values()];}
function acceptState(data){if(data?.partial&&app.state){app.state={...app.state,...data,items:mergeRows(app.state.items,data.items),extras:mergeRows(app.state.extras,data.extras),contributions:mergeRows(app.state.contributions,data.contributions)};}else app.state=data;}
async function loadState(failLoud=true){if(!app.access||app.polling)return false;app.polling=true;try{app.pollTicks+=1;const receiptRefresh=app.state?.session?.module==='recepcion'&&app.pollTicks%4===0,complete=!app.state||receiptRefresh;const data=await rpc('op_invitado_estado',{p_acceso:app.access,p_completo:complete,p_codigo:complete?null:(app.selected||null)});if(!data?.ok){if(failLoud)showError(data?.error);return false;}acceptState(data);renderWorkspace();$('guest-last-sync').textContent=new Date().toLocaleTimeString('es-UY',{hour:'2-digit',minute:'2-digit'});return true;}catch(e){if(failLoud&&/paus|finaliz|válido|revoc/i.test(e.message||''))showError(e.message);else if(failLoud)toast('Reconectando…','error');return false;}finally{app.polling=false;}}
function startWorkspace(){setHidden('guest-entry',true);setHidden('guest-workspace',false);const guest=app.state.guest||{},session=app.state.session||{};$('workspace-module').textContent=label(session.module);$('workspace-session').textContent=[session.name,session.route].filter(Boolean).join(' · ');$('workspace-name').textContent=guest.name||'Invitado';$('workspace-photo').src=validPhoto(app.photo)?app.photo:'sucan_logo.png';$('guest-search-help').textContent=session.module==='reposicion'?'Buscá un producto de la reposición o un extra.':session.module==='recepcion'?'Buscá en el remito o agregá mercadería recibida fuera de él.':'Buscá por nombre, código o código de barras.';finishBoot();clearInterval(app.poll);app.poll=setInterval(()=>loadState(true),1250);renderWorkspace();}

function productFor(code,item){return app.products.find(p=>clean(p.codigo)===clean(code))||{codigo:code,nombre:item?.name||item?.nombre||code,barras:item?.barcode||item?.barras||''};}
function stateItem(code){return(app.state?.items||[]).find(row=>clean(row.code)===clean(code));}
function ownContribution(code){return num((app.state?.contributions||[]).find(row=>clean(row.code)===clean(code))?.quantity);}
function actionButton(text,onclick,kind='guest-secondary'){return`<button class="${kind}" type="button" onclick="${onclick}">${text}</button>`;}
function renderWorkspace(){if(!app.state||$('guest-workspace').hidden)return;const moduleName=app.state.session?.module;if(moduleName==='inventario')renderInventory();else if(moduleName==='reposicion')renderRepo();else renderReceipt();}

function renderInventory(){
  let item=stateItem(app.selected),product=productFor(app.selected,item);if(!app.selected){const own=(app.state.contributions||[])[0];if(own){app.selected=own.code;item=stateItem(app.selected);product=productFor(app.selected,item);}}
  const content=$('guest-module-content');
  if(!app.selected){content.innerHTML=`<div class="guest-empty"><span>⌕</span><h2>Buscá el primer producto</h2><p>Usá el buscador o la cámara. Cada unidad que registres se sincroniza inmediatamente con el inventario.</p></div>${renderRecent('Mis últimos conteos',app.state.contributions,'quantity')}`;return;}
  const total=num(item?.quantity),own=ownContribution(app.selected);
  content.innerHTML=`<article class="guest-product-card"><span class="guest-product-status">Producto seleccionado</span><h2>${escHtml(product.nombre)}</h2><div class="guest-product-meta">SKU ${escHtml(product.codigo)}${product.barras?` · Barras ${escHtml(product.barras)}`:''}</div><div class="guest-quantities"><div class="guest-quantity"><span>Total sesión</span><strong>${total}</strong></div><div class="guest-quantity ok"><span>Mi aporte</span><strong>${own}</strong></div><div class="guest-quantity"><span>Última acción</span><strong>+1</strong></div></div><div class="guest-main-actions">${actionButton('✓ Agregar 1 unidad',`guestInventoryDelta('${js(app.selected)}',1)`,'guest-primary')}${actionButton('Editar mi aporte',`guestEditInventory('${js(app.selected)}')`)}</div><div class="guest-quick-actions">${actionButton('+5',`guestInventoryDelta('${js(app.selected)}',5)`)}${actionButton('−1',`guestInventoryDelta('${js(app.selected)}',-1)`)}${actionButton('Cambiar producto','focusGuestSearch()')}</div></article>${renderRecent('Mis últimos conteos',app.state.contributions,'quantity')}`;
}
function repoPending(row){return!row.not_found&&!row.closed_incomplete&&num(row.prepared)<num(row.requested);}
function myRepoItem(){const id=app.state?.guest?.client_id;return(app.state?.items||[]).find(row=>row.assigned_client===id&&repoPending(row));}
function renderRepo(){
  const content=$('guest-module-content'),mine=myRepoItem(),pending=(app.state.items||[]).filter(repoPending);
  if(!mine){
    if(!pending.length){content.innerHTML=`<div class="guest-empty"><span>✓</span><h2>No quedan productos para recoger</h2><p>Todos los productos fueron completados, informados como no encontrados o están siendo preparados por otras personas.</p></div>${renderRepoList()}`;return;}
    content.innerHTML=`<div class="guest-empty"><span>↻</span><h2>Buscando tu próximo producto…</h2><p>El sistema te asignará uno diferente al de los demás colaboradores.</p></div>${renderRepoList()}`;
    if(!app.claiming){app.claiming=true;operate('repo_claim','',null,{},false).finally(()=>app.claiming=false);}return;
  }
  app.selected=mine.code;const remain=Math.max(0,num(mine.requested)-num(mine.prepared)),orders=Array.isArray(mine.orders)?mine.orders:[];
  content.innerHTML=`<article class="guest-product-card"><span class="guest-product-status">Producto asignado para recoger</span><h2>${escHtml(mine.name)}</h2><div class="guest-product-meta">SKU ${escHtml(mine.code)}${mine.barcode?` · Barras ${escHtml(mine.barcode)}`:''}${orders.length?' · Incluye pedido aceptado':''}</div><div class="guest-quantities"><div class="guest-quantity"><span>Solicitado</span><strong>${num(mine.requested)}</strong></div><div class="guest-quantity ok"><span>Recogido</span><strong>${num(mine.prepared)}</strong></div><div class="guest-quantity warn"><span>Falta</span><strong>${remain}</strong></div></div><div class="guest-main-actions">${actionButton(`✓ Encontrado · ${remain||1} un.`,`guestRepoFound('${js(mine.code)}')`,'guest-primary')}${actionButton('Editar cantidad',`guestRepoEdit('${js(mine.code)}')`)}</div><div class="guest-quick-actions">${actionButton('+1',`guestRepoSet('${js(mine.code)}',${num(mine.prepared)+1})`)}${actionButton('No encontrado',`guestRepoNotFound('${js(mine.code)}')`)}${actionButton('Saltear',`guestRepoSkip('${js(mine.code)}')`)}</div></article>${renderRepoList()}`;
}
function renderRepoList(){const rows=(app.state.items||[]).filter(repoPending).slice(0,8);return`<section class="guest-list-card"><div class="guest-list-head"><h3>Pendientes en la sesión</h3><span>${(app.state.items||[]).filter(repoPending).length}</span></div><div class="guest-list">${rows.length?rows.map(row=>`<div class="guest-list-row"><div><strong>${escHtml(row.name)}</strong><span>SKU ${escHtml(row.code)}${row.assigned_name?` · En preparación por ${escHtml(row.assigned_name)}`:''}</span></div><b>${Math.max(0,num(row.requested)-num(row.prepared))}</b></div>`).join(''):'<div class="guest-empty">Sin pendientes.</div>'}</div></section>`;}
function renderReceipt(){
  const content=$('guest-module-content'),client=app.state?.guest?.client_id,item=stateItem(app.selected),mine=item&&item.assigned_client===client?item:(app.state.items||[]).find(row=>row.assigned_client===client);
  if(!mine){app.selected='';const pending=(app.state.items||[]).filter(r=>!r.controlled_at);content.innerHTML=`<div class="guest-empty"><span>⌕</span><h2>Buscá lo que llegó</h2><p>Al abrir o escanear un producto quedará reservado para vos. Las demás personas recibirán productos diferentes.</p></div>${renderReceiptList(pending)}`;return;}
  app.selected=mine.code;
  const received=num(mine.received),expected=num(mine.expected),difference=received-expected;
  content.innerHTML=`<article class="guest-product-card"><span class="guest-product-status">Reservado para vos</span><h2>${escHtml(mine.name)}</h2><div class="guest-product-meta">SKU ${escHtml(mine.code)}${mine.barcode?` · Barras ${escHtml(mine.barcode)}`:''}</div><div class="guest-quantities"><div class="guest-quantity"><span>Esperado</span><strong>${expected}</strong></div><div class="guest-quantity ok"><span>Recibido</span><strong>${received}</strong></div><div class="guest-quantity ${difference<0?'warn':'ok'}"><span>${difference<0?'Falta':'Diferencia'}</span><strong>${difference}</strong></div></div><div class="guest-main-actions">${actionButton(`✓ Confirmar ${expected} ${expected===1?'unidad':'unidades'}`,`guestReceiptConfirm('${js(mine.code)}')`,'guest-primary')}${actionButton('Modificar cantidad',`guestReceiptEdit('${js(mine.code)}')`)}</div><div class="guest-quick-actions">${actionButton('+1 unidad',`guestReceiptAdd('${js(mine.code)}',1)`)}${actionButton('Escanear',`openGuestScanner()`)}${actionButton('Liberar producto',`guestReceiptRelease('${js(mine.code)}')`)}</div></article>${renderReceiptList((app.state.items||[]).filter(r=>!r.controlled_at))}`;
}
function renderReceiptList(rows){const client=app.state?.guest?.client_id;return`<section class="guest-list-card"><div class="guest-list-head"><h3>Pendientes del remito</h3><span>${rows.length}</span></div><div class="guest-list">${rows.slice(0,8).map(row=>{const busy=row.assigned_client&&row.assigned_client!==client;return`<button class="guest-list-row" type="button" onclick="selectGuestProduct('${js(row.code)}')"><div><strong>${escHtml(row.name)}</strong><span>SKU ${escHtml(row.code)} · ${busy?`Controlando: ${escHtml(row.assigned_name||'otra persona')}`:`Recibido ${num(row.received)} de ${num(row.expected)}`}</span></div><b>${busy?'•':Math.max(0,num(row.expected)-num(row.received))}</b></button>`;}).join('')||'<div class="guest-empty">No quedan productos pendientes.</div>'}</div></section>`;}
function renderRecent(title,rows,key){const list=(rows||[]).filter(r=>num(r[key])>0).slice(0,8);return`<section class="guest-list-card"><div class="guest-list-head"><h3>${escHtml(title)}</h3><span>${list.length}</span></div><div class="guest-list">${list.map(row=>{const product=productFor(row.code,row);return`<button class="guest-list-row" type="button" onclick="selectGuestProduct('${js(row.code)}')"><div><strong>${escHtml(product.nombre)}</strong><span>SKU ${escHtml(row.code)}</span></div><b>${num(row[key])}</b></button>`;}).join('')||'<div class="guest-empty">Todavía no registraste productos.</div>'}</div></section>`;}
function js(value){return clean(value).replace(/\\/g,'\\\\').replace(/'/g,"\\'").replace(/[\r\n]/g,' ').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}

async function operate(action,code,quantity,detail={},notify=true){if(app.operating)return null;app.operating=true;try{const rpcName=app.state?.session?.module==='recepcion'?'op_invitado_recepcion_operar':'op_invitado_operar',data=await rpc(rpcName,{p_acceso:app.access,p_accion:action,p_codigo:code||null,p_cantidad:quantity==null?null:Math.round(quantity),p_detalle:detail||{}});if(!data?.ok)throw new Error(data?.error||'No se pudo guardar.');acceptState(data);renderWorkspace();if(notify)toast('Actualizado en tiempo real');return data;}catch(e){toast(e.message||'No se pudo guardar','error');await loadState(false);return null;}finally{app.operating=false;}}

function searchProducts(query){const q=clean(query);if(q.length<2)return[];let ranked=window.SucaneitorSearch?.rankProducts(app.index,q,null,45).map(r=>r.product)||app.products.filter(p=>`${p.codigo} ${p.barras} ${p.nombre}`.toLowerCase().includes(q.toLowerCase())).slice(0,45);const code=q.toUpperCase(),direct=app.products.filter(p=>clean(p.codigo).toUpperCase()===code||window.SucaneitorBarcode?.matchesBarcode(p.barras,q));const sessionCodes=new Set((app.state?.items||[]).map(r=>clean(r.code)));ranked=[...direct,...ranked].filter((p,i,a)=>a.findIndex(x=>clean(x.codigo)===clean(p.codigo))===i);ranked.sort((a,b)=>Number(sessionCodes.has(clean(b.codigo)))-Number(sessionCodes.has(clean(a.codigo))));return ranked.slice(0,30);}
function onSearch(){const box=$('guest-search-results'),q=$('guest-search').value,results=searchProducts(q);if(clean(q).length<2){box.hidden=true;box.innerHTML='';return;}box.hidden=false;box.innerHTML=results.length?results.map(product=>{const inside=Boolean(stateItem(product.codigo));return`<button class="guest-search-result" type="button" data-code="${escHtml(product.codigo)}" onclick="selectGuestProduct(this.dataset.code)"><span><strong>${escHtml(product.nombre)}</strong><span>SKU ${escHtml(product.codigo)}${product.barras?` · Barras ${escHtml(product.barras)}`:''}${inside?' · Incluido en la sesión':' · Fuera de la lista'}</span></span><b>→</b></button>`;}).join(''):'<div class="guest-empty">No encontramos coincidencias.</div>';}
function clearSearch(){const input=$('guest-search');input.value='';$('guest-search-results').hidden=true;input.focus();}
function focusSearch(){const input=$('guest-search');input.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>input.focus(),250);}
async function selectProduct(code){clearSearch();const moduleName=app.state.session.module,item=stateItem(code),product=productFor(code,item);if(moduleName==='inventario'){app.selected=code;renderInventory();return;}if(moduleName==='reposicion'){if(item){const result=await operate('repo_claim',code,null,{},false);if(result){app.selected=code;toast('Producto asignado');}return;}await addOutside(product,'repo_extra_add');return;}if(item){const result=await operate('receipt_claim',code,null,{},false);if(result&&stateItem(code)?.assigned_client===app.state?.guest?.client_id){app.selected=code;toast('Producto reservado para vos');renderReceipt();}return;}await addOutside(product,'receipt_extra_add');}
async function addOutside(product,action){const value=await quantityDialog({title:'Producto fuera de la lista',message:`${product.nombre} no está incluido. Si llegó igualmente, registralo como mercadería extra.`,value:1,confirmText:'Agregar como extra'});if(value===null)return;await operate(action,product.codigo,value,{name:product.nombre,barcode:product.barras});}

function modal(options={}){return new Promise(resolve=>{app.modalResolve=resolve;$('guest-modal-icon').textContent=options.icon||'?';$('guest-modal-title').textContent=options.title||'Confirmar';$('guest-modal-message').textContent=options.message||'';$('guest-modal-body').innerHTML=options.body||'';$('guest-modal-error').textContent='';$('guest-modal-confirm').textContent=options.confirmText||'Confirmar';$('guest-modal-cancel').textContent=options.cancelText||'Cancelar';$('guest-modal-layer').hidden=false;$('guest-modal-cancel').onclick=()=>closeModal(null);$('guest-modal-confirm').onclick=()=>{try{const value=options.validate?options.validate():true;if(value&&value.error){$('guest-modal-error').textContent=value.error;return;}closeModal(value);}catch(e){$('guest-modal-error').textContent=e.message;}};setTimeout(()=>$(options.focus||'')?.focus(),40);});}
function closeModal(value){$('guest-modal-layer').hidden=true;const resolve=app.modalResolve;app.modalResolve=null;resolve?.(value);}
function quantityDialog({title,message,value=1,confirmText='Confirmar cantidad'}){return modal({title,message,icon:'#',confirmText,body:`<label>Cantidad<input id="guest-quantity-input" type="number" inputmode="numeric" min="0" max="999999" value="${Math.max(0,Math.round(value))}"></label>`,focus:'guest-quantity-input',validate:()=>{const q=Number($('guest-quantity-input').value);return Number.isInteger(q)&&q>=0&&q<=999999?q:{error:'Ingresá una cantidad válida.'};}});}

async function inventoryDelta(code,delta){if(delta<0&&ownContribution(code)<Math.abs(delta)){toast('Solo podés descontar unidades agregadas por vos','error');return;}await operate('inventory_delta',code,delta,{name:productFor(code).nombre,barcode:productFor(code).barras});}
async function editInventory(code){const own=ownContribution(code),value=await quantityDialog({title:'Editar mi aporte',message:'Solo se modifican las unidades que registraste vos.',value:own});if(value===null||value===own)return;await inventoryDelta(code,value-own);}
async function repoFound(code){const item=stateItem(code),target=num(item?.requested),current=num(item?.prepared),value=await quantityDialog({title:'Confirmar producto encontrado',message:`Solicitado: ${target} · recogido hasta ahora: ${current}. Se agregará 1 unidad; modificala solamente si ya contaste más unidades físicas.`,value:current+1,confirmText:'Confirmar cantidad'});if(value!==null)await operate('repo_set',code,value);}
async function repoEdit(code){const item=stateItem(code),value=await quantityDialog({title:'Modificar cantidad recogida',message:item?.name||code,value:num(item?.prepared),confirmText:'Guardar cantidad'});if(value!==null)await operate('repo_set',code,value);}
async function repoNotFound(code){const item=stateItem(code),value=await modal({title:'Producto no encontrado',message:item?.name||code,icon:'!',confirmText:'Registrar y continuar',body:'<label>Motivo (opcional)<select id="guest-nf-reason"><option value="">Sin especificar</option><option value="stock_insuficiente">Stock insuficiente</option><option value="otro">Otro</option></select></label><label>Comentario (opcional)<textarea id="guest-nf-comment" maxlength="500" placeholder="Detalle adicional…"></textarea></label>',validate:()=>({reason:$('guest-nf-reason').value,reason_label:$('guest-nf-reason').selectedOptions[0].textContent,comment:clean($('guest-nf-comment').value)})});if(value)await operate('repo_not_found',code,null,value);}
async function repoSkip(code){await operate('repo_release',code,null,{},false);toast('Producto liberado para otra persona');}
async function receiptConfirm(code){const item=stateItem(code),value=await quantityDialog({title:'Confirmar recepción',message:`El remito indica ${num(item?.expected)} ${num(item?.expected)===1?'unidad':'unidades'}. Confirmá esa cantidad o modificala si llegó una cantidad diferente.`,value:num(item?.expected),confirmText:'Confirmar cantidad recibida'});if(value!==null){await operate('receipt_set',code,value);app.selected='';renderReceipt();}}
async function receiptEdit(code){const item=stateItem(code),value=await quantityDialog({title:'Modificar cantidad recibida',message:`Esperado según remito: ${num(item?.expected)}.`,value:num(item?.received),confirmText:'Guardar cantidad'});if(value!==null){await operate('receipt_set',code,value);app.selected='';renderReceipt();}}
async function receiptAdd(code,delta){await operate('receipt_add',code,delta);app.selected='';renderReceipt();}
async function receiptRelease(code){await operate('receipt_release',code,null,{},false);app.selected='';toast('Producto liberado para otra persona');renderReceipt();}

function productByBarcode(barcode){const fromState=(app.state.items||[]).find(row=>window.SucaneitorBarcode?.matchesBarcode(row.barcode,barcode));if(fromState)return productFor(fromState.code,fromState);return app.products.find(product=>window.SucaneitorBarcode?.matchesBarcode(product.barras,barcode));}
async function scanned(barcode){await closeScanner();const product=productByBarcode(barcode);if(!product){toast(`Código ${barcode} no encontrado en el padrón`,'error');return;}const moduleName=app.state.session.module,item=stateItem(product.codigo);if(moduleName==='inventario'){app.selected=product.codigo;const value=await quantityDialog({title:'Producto escaneado',message:`${product.nombre}. Se agregará una unidad; podés modificar la cantidad.`,value:1,confirmText:'Agregar al inventario'});if(value)await operate('inventory_delta',product.codigo,value,{name:product.nombre,barcode:product.barras});return;}if(moduleName==='reposicion'&&item){const claimed=await operate('repo_claim',product.codigo,null,{},false);if(!claimed)return;const current=stateItem(product.codigo),value=await quantityDialog({title:'Producto comprobado',message:`${product.nombre}. Se agregará 1 unidad; podés modificar la cantidad total recogida.`,value:num(current?.prepared)+1,confirmText:'Confirmar cantidad'});if(value!==null)await operate('repo_set',product.codigo,value);return;}if(moduleName==='recepcion'&&item){const claimed=await operate('receipt_claim',product.codigo,null,{},false);if(!claimed||stateItem(product.codigo)?.assigned_client!==app.state?.guest?.client_id)return;app.selected=product.codigo;const current=stateItem(product.codigo),value=await quantityDialog({title:'Producto escaneado',message:`${product.nombre}. Se agregará 1 unidad; podés modificar la cantidad total recibida.`,value:num(current?.received)+1,confirmText:'Confirmar cantidad'});if(value!==null){await operate('receipt_set',product.codigo,value);app.selected='';}else await operate('receipt_release',product.codigo,null,{},false);return;}await addOutside(product,moduleName==='reposicion'?'repo_extra_add':'receipt_extra_add');}
async function openScanner(){const layer=$('guest-scanner');layer.hidden=false;$('guest-scanner-status').textContent='La cámara detectará el código automáticamente.';try{if(typeof Html5Qrcode!=='function')throw new Error('Escáner no disponible');app.scanner=new Html5Qrcode('guest-scanner-reader');const width=Math.min(innerWidth-40,480);await app.scanner.start({facingMode:'environment'},{fps:15,qrbox:{width:Math.max(220,Math.round(width*.82)),height:150},aspectRatio:1.333},decoded=>{if(app.scanner)scanned(decoded);},()=>{});}catch(e){$('guest-scanner-status').textContent='No se pudo abrir la cámara. Revisá el permiso de cámara e intentá otra vez.';toast('No se pudo iniciar la cámara','error');}}
async function closeScanner(){const scanner=app.scanner;app.scanner=null;if(scanner){try{await scanner.stop();}catch(_){}try{await scanner.clear();}catch(_){}}$('guest-scanner').hidden=true;$('guest-scanner-reader').innerHTML='';}

window.clearGuestSearch=clearSearch;window.focusGuestSearch=focusSearch;window.selectGuestProduct=selectProduct;window.guestInventoryDelta=inventoryDelta;window.guestEditInventory=editInventory;window.guestRepoFound=repoFound;window.guestRepoEdit=repoEdit;window.guestRepoSet=(c,q)=>operate('repo_set',c,q);window.guestRepoNotFound=repoNotFound;window.guestRepoSkip=repoSkip;window.guestReceiptConfirm=receiptConfirm;window.guestReceiptEdit=receiptEdit;window.guestReceiptAdd=receiptAdd;window.guestReceiptRelease=receiptRelease;window.openGuestScanner=openScanner;window.closeGuestScanner=closeScanner;
$('guest-photo-input').addEventListener('change',onPhoto);$('guest-join-form').addEventListener('submit',join);$('guest-search').addEventListener('input',onSearch);window.addEventListener('beforeunload',()=>{clearInterval(app.poll);closeScanner();});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&app.access)loadState(true);});
initialize();
})();
