const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const migration=read('supabase/migrations/20260824200000_acceso_invitado_qr.sql');
const repoParityMigration=read('supabase/migrations/20260825234500_reposicion_invitada_paridad.sql');
const operations=read('operaciones/index.html');
const host=read('operaciones/session-invite.js');
const guestHtml=read('operaciones/invitado.html');
const guestJs=read('operaciones/invitado.js');
const guestCss=read('operaciones/invitado.css');

assert.match(migration,/token_hash text not null unique/,'La base solo debe guardar el hash del QR');
assert.match(migration,/access_hash text not null unique/,'La credencial del invitado debe guardarse cifrada como hash');
assert.match(migration,/revoke all on table public\.op_invitaciones_sesion from anon,authenticated/,'Las tablas de invitaciones no deben exponerse directamente');
assert.match(migration,/grant execute on function public\.op_invitacion_preview\(text\) to anon,authenticated/,'El enlace debe poder validarse sin iniciar sesión');
assert.match(migration,/grant execute on function public\.op_invitado_operar\(text,text,text,integer,jsonb\) to anon,authenticated/,'El invitado debe operar solo mediante la función controlada');
assert.match(migration,/grant execute on function public\.op_invitado_estado\(text,boolean,text\) to anon,authenticated/,'El invitado debe consultar únicamente el estado controlado');
assert.doesNotMatch(migration,/grant (select|insert|update|delete).*op_invit/i,'Anon no debe recibir permisos directos de lectura o escritura');
assert.match(migration,/La fotografía es obligatoria/,'El ingreso debe exigir foto');
assert.match(migration,/Solamente el creador o un administrador puede invitar colaboradores/,'Solo el creador o administrador debe generar accesos');
assert.match(migration,/repo_claim[\s\S]*for update skip locked/,'Reposición debe asignar productos distintos de forma concurrente');
assert.match(migration,/op_cerrar_invitaciones_sesion[\s\S]*activa=false/,'Cerrar una sesión debe invalidar su invitación');
assert.match(migration,/last_seen<now\(\)-interval '30 days'/,'Las fotos deben tener limpieza por antigüedad');

assert.match(operations,/id="session-invite-fab"/,'El creador debe tener el acceso flotante');
assert.match(operations,/qrcodejs@1\.0\.0/,'Debe poder generar QR en el navegador');
assert.match(host,/\/operaciones\/invitado#/,'El token debe viajar en el fragmento y no en registros del servidor');
assert.match(host,/Compartir enlace/,'Además del QR debe existir un enlace compartible');
assert.match(host,/Pausar acceso|Reactivar acceso/,'El creador debe poder pausar y reactivar');
assert.match(host,/removeSessionGuest/,'El creador debe poder expulsar invitados');

assert.match(guestHtml,/capture="user"/,'El teléfono debe abrir la cámara frontal para la identificación');
assert.match(guestHtml,/interactive-widget=resizes-content/,'Android debe redimensionar el contenido en lugar de desplazar la página al abrir el teclado');
assert.match(guestHtml,/Acceso limitado a esta sesión/,'La limitación debe ser visible');
assert.doesNotMatch(guestHtml,/<button[^>]*>[^<]*(descargar|configuración|cambiar de módulo)/i,'La pantalla operativa no debe ofrecer acciones privilegiadas');
assert.match(guestJs,/setInterval\(\(\)=>loadState\(true\),1250\)/,'El estado debe sincronizarse continuamente');
assert.match(guestJs,/p_completo:complete/,'Después de la primera carga se deben pedir actualizaciones livianas');
assert.match(guestJs,/repo_claim/,'El invitado debe poder recibir un producto de reposición');
assert.match(guestJs,/inventory_delta/,'El invitado debe poder contar inventario');
assert.match(guestJs,/receipt_set/,'El invitado debe poder controlar cantidades recibidas');
assert.match(guestJs,/Producto fuera de la lista/,'Los extras deben registrarse de forma explícita');
assert.doesNotMatch(guestJs,/Pendientes en la sesión/,'El invitado no debe ver la lista general de pendientes');
assert.doesNotMatch(guestJs,/function renderRepoList\(/,'La vista QR no debe reconstruir la lista general de reposición');
assert.match(guestHtml,/Buscar\/agregar producto/,'El acceso QR debe ofrecer el buscador explícito del padrón');
assert.match(guestJs,/Pedido por esta reposición/,'Cada resultado debe identificar los productos solicitados');
assert.match(guestJs,/No pedido · se agregará como extra/,'Cada resultado fuera de la reposición debe quedar identificado');
assert.match(guestJs,/repo_extra_set/,'Un extra existente debe poder modificarse desde el buscador');
assert.match(guestJs,/matchesBarcode/,'El escáner debe usar las variantes del código de barras central');
assert.match(guestJs,/openGuestRepoScanner/,'La tarjeta de Reposición debe ofrecer un escáner de comprobación contextual');
assert.match(guestJs,/scanMode==='verify'/,'El escáner debe rechazar un producto distinto al asignado');
assert.match(guestJs,/Vas a modificar una cantidad/,'Toda modificación debe advertir antes de guardar');
assert.match(guestJs,/requestRepoQuantity\(code,current\+num\(delta\)/,'Los accesos rápidos deben confirmar el antes y el después');
assert.doesNotMatch(guestJs,/guestRepoSet=/,'No debe existir un botón que cambie cantidades sin confirmación');
assert.match(guestJs,/El motivo se solicita siempre, pero es opcional/,'Saltear debe abrir el motivo opcional');
assert.match(guestJs,/op_invitado_reposicion_liberar/,'El salto debe pasar por una operación auditada');
assert.match(guestJs,/clearSearch\(false\)/,'Al elegir un producto debe cerrarse la búsqueda sin volver a abrir el teclado');
assert.match(guestJs,/focus\(\{preventScroll:true\}\)/,'El foco móvil no debe desplazar la pantalla automáticamente');
assert.match(guestJs,/centerGuestProduct\(mine\.code\)/,'Cada nuevo producto de reposición debe centrarse una sola vez');
assert.match(guestJs,/reader\.getBoundingClientRect\(\)/,'El visor debe calcularse con el espacio real disponible');
assert.match(guestJs,/scannerBusy=true/,'Una lectura debe bloquear duplicados mientras se reinicia la cámara');
assert.doesNotMatch(guestJs,/aspectRatio:1\.333/,'La cámara móvil no debe conservar una relación de aspecto rígida entre lecturas');
assert.match(repoParityMigration,/'requested_reposition',i\.pedido_reposicion/,'El invitado debe ver el desglose de la cantidad física');
assert.match(repoParityMigration,/create or replace function public\.op_invitado_reposicion_liberar/,'Debe existir una operación dedicada para saltear');
assert.match(repoParityMigration,/item\.asignado_cliente is distinct from g\.cliente_id/,'Solo el invitado asignado puede liberar el producto');
assert.match(repoParityMigration,/'invitado_salteado'/,'El salto y su motivo deben quedar auditados');
assert.match(repoParityMigration,/security definer[\s\S]*set search_path=public,extensions,pg_temp/,'La operación pública debe fijar su search_path');
assert.match(repoParityMigration,/revoke all on function public\.op_invitado_reposicion_liberar\(text,text,jsonb\) from public/,'La función no debe quedar abierta por defecto');
assert.match(repoParityMigration,/grant execute on function public\.op_invitado_reposicion_liberar\(text,text,jsonb\) to anon,authenticated/,'El QR debe ejecutar únicamente la función controlada');
assert.match(guestCss,/\.guest-pick-target/,'La cantidad a juntar debe destacarse visualmente');
assert.match(guestCss,/\.guest-scan-guidance/,'La tarjeta debe explicar dónde comprobar el producto');
assert.match(guestCss,/@media\(max-width:620px\)/,'La vista debe adaptarse a teléfonos');
assert.match(guestCss,/@media\(max-width:370px\)/,'La vista debe contemplar teléfonos angostos');
assert.match(guestCss,/body\.guest-overlay-open\{position:fixed/,'Los diálogos y la cámara deben inmovilizar el fondo en iPhone y Android');
assert.match(guestCss,/\.guest-search-card\{position:relative;top:auto\}/,'El buscador móvil no debe saltar al variar su altura');
assert.match(guestHtml,/invitado\.js\?v=repo-orders-v1/,'El navegador debe cargar los textos actuales sin conservar caché anterior');

console.log('guest-access: OK');
