const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ui=require('../operaciones/receipt-orders');
const order={id:'00000000-0000-0000-0000-000123456700',cliente:'Estefanía',estado:'transito',relation:'fecha_productos',linked:false,pedido_productos:[{id:'p',codigo:'A',nombre:'Alimento',cantidad:3,cantidad_recibida:1,en_remito:true,disponible:1}]};
assert.equal(ui.pending(order),2);assert.equal(ui.code(order.id),'234567');assert.equal(ui.canLink(order),true);
for(const relation of ['otro_remito','fecha_posterior','sin_enviar','sin_productos'])assert.equal(ui.canLink({...order,relation}),false);
assert.equal(ui.canLink({...order,estado:'pendiente'}),false);
assert.equal(ui.filtered([order],'estefania').length,1);assert.equal(ui.filtered([order],'A').length,1);assert.equal(ui.filtered([order],'234567').length,1);
assert.equal(ui.filtered([order],'','linked').length,0);assert.equal(ui.filtered([order],'','notify').length,0);
assert.equal(ui.matching([order],'A').length,1);assert.equal(ui.matching([order],'B').length,0);
assert.deepEqual(ui.allocation({...order,pedido_productos:[...order.pedido_productos,{...order.pedido_productos[0],id:'p2'}]}).map(p=>p.quantity),[1,0]);
assert.equal(ui.html('<img onerror="x">'), '&lt;img onerror=&quot;x&quot;&gt;');
const elements=new Map();const element=id=>{if(!elements.has(id))elements.set(id,{innerHTML:'',value:'',classList:{toggle(){}},hidden:false});return elements.get(id);};
const state={origin:'PDE',destination:'MDO',document_number:'R1',estado:'en_control',order_panel:{can_receive:true,can_notify:true,orders:[{...order,cliente:'<img src=x onerror=alert(1)>',pedido_productos:[{...order.pedido_productos[0],nombre:'<script>bad</script>'}]}]}};
const context={window:{},document:{getElementById:element},receiptState:state,receiptCurrentCode:'A',receiptCanEdit:()=>true,console};
vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../operaciones/receipt-orders'),'utf8'),context);context.SucanReceiptOrders=context.window.SucanReceiptOrders;
context.renderReceiptOrders();
const html=element('receipt-expected-orders').innerHTML;
assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>bad'));assert.ok(html.includes('&lt;img'));
assert.ok(html.includes('Vincular y registrar recepción'));assert.ok(html.includes('?module=pedidos&pedido='));assert.ok(html.includes('target="_blank" rel="noopener"'));
assert.ok(element('receipt-order-notice').innerHTML.includes('Ver pedido #234567'));
state.order_panel.can_receive=false;context.renderReceiptOrders();assert.ok(!element('receipt-expected-orders').innerHTML.includes('data-receive-order'));
state.order_panel.orders[0].cliente_aviso_pendiente=true;state.order_panel.orders[0].telefono='099000000';state.order_panel.orders[0].estado='completo';
context.renderReceiptOrders();assert.ok(element('receipt-expected-orders').innerHTML.includes('Abrir WhatsApp'));assert.ok(element('receipt-expected-orders').innerHTML.includes('El mensaje no se envía automáticamente'));
state.order_panel.can_notify=false;context.renderReceiptOrders();assert.ok(!element('receipt-expected-orders').innerHTML.includes('data-contact-order'));
console.log('receipt-orders: rendering, escaping, links, filters, allocation and permissions OK');
