const fs=require('fs'),assert=require('assert');
const page=fs.readFileSync('reservas/index.html','utf8'),js=fs.readFileSync('reservas/reservas.js','utf8'),css=fs.readFileSync('reservas/reservas.css','utf8'),lookupPage=fs.readFileSync('reserva.html','utf8'),lookup=fs.readFileSync('reservas/consulta.js','utf8'),root=fs.readFileSync('index.html','utf8'),rootJs=fs.readFileSync('app.js','utf8'),receipt=fs.readFileSync('operaciones/receipt-orders.js','utf8');
assert.match(root,/href="\/reservas"[\s\S]+Control de reservas/,'El inicio debe mostrar el módulo');
assert.doesNotMatch(page,/id="access-key"|Contraseña de la empresa/,'El enlace de creación no debe pedir contraseña');
assert.doesNotMatch(page,/id="access-name"|access-form/,'El enlace debe abrir directamente el formulario');
assert.match(page,/Enlace para crear reservas[\s\S]*sin iniciar sesión[\s\S]*no permite consultar, modificar ni controlar/,'La configuración debe explicar el alcance de solo creación');
assert.match(page,/id="guide-button"/,'El módulo debe ofrecer instrucciones operativas sin salir del flujo');
assert.doesNotMatch(page,/id="new-reason"/,'La creación no debe imponer un único motivo general');
assert.match(page,/Pedido a otro local[\s\S]*Esperando proveedor[\s\S]*Disponible en el local/,'La configuración explica los tres orígenes operativos');
assert.match(page,/Productos y origen[\s\S]*seleccioná el origen de cada uno[\s\S]*Dividir origen/,'La creación explica el origen independiente y la división de cantidades');
assert.match(page,/data-product-search-type="nombre"[\s\S]*data-product-search-type="codigo"[\s\S]*data-product-search-type="barras"/,'El buscador de reservas ofrece los mismos modos que el conteo de inventario');
assert.match(page,/operaciones\/search-engine\.js\?v=search-fast-v6/,'Reservas reutiliza el motor de búsqueda del conteo de inventario');
assert.match(page,/id="new-responsible"/,'La creación pide responsable');
assert.match(page,/id="new-purpose"[\s\S]*Retiro del cliente en el local[\s\S]*Reparto del local[\s\S]*Pedido web[\s\S]*Traslado interno entre locales/,'La reserva debe explicar para qué se separa la mercadería');
assert.match(page,/id="new-web-delivery"[\s\S]*Retiro en el local[\s\S]*Reparto del local[\s\S]*Agencia o correo/,'Un pedido web debe indicar cómo se entregará');
assert.match(page,/id="schedule-type"[\s\S]*value="proveedor"[\s\S]*value="local"[\s\S]*schedule-days/,'El administrador configura calendarios por proveedor o local de origen');
assert.match(page,/id="customer-document"/,'Los datos opcionales incluyen documento');
assert.match(page,/data-view="history"/,'Existe historial');
assert.match(page,/id="settings-printer"/,'La ruta de impresora es configurable');
assert.match(page,/id="settings-location"/,'El lugar fijo de las reservas debe poder configurarse por tienda');
assert.doesNotMatch(page,/id="settings-hours"/,'El plazo exacto de 48 horas no debe ser editable');
assert.match(page,/id="print-calibration"/,'La configuración debe ofrecer la prueba física de la BSC10');
assert.match(page,/jsbarcode@3\.12\.3/,'La calibración usa un Code 128 real y una versión fijada');
assert.doesNotMatch(js,/op_reserva_invitado_entrar|company-access/,'El enlace de creación no debe iniciar una sesión temporal ni pedir la clave empresarial');
assert.match(js,/if\(state\.linkToken\)\{state\.publicCreate=true;state\.access=state\.linkToken;return openApp\(\);\}/,'El token del local debe abrir directamente la creación');
assert.match(js,/if\(state\.publicCreate&&view!=='new'\)view='new'/,'El enlace no puede navegar a vistas de gestión');
assert.match(js,/state\.publicCreate\?'':state\.actor\?\.name/,'El responsable se completa dentro de la reserva y no antes de abrir el formulario');
assert.match(js,/responsable:responsible/,'La creación debe enviar el nombre del responsable sin provocar un error de variable');
assert.match(js,/const sourceLabels=\{local:'Disponible en el local',proveedor:'Esperando proveedor',pedido_local:'Pedido a otro local'\}/,'La interfaz ofrece los tres orígenes en cada producto');
assert.match(page,/class="tab admin-only"[\s\S]*data-view="settings"[\s\S]*hidden>Configuración/,'La pestaña de configuración comienza oculta');
assert.match(page,/class="view admin-only" id="view-settings" hidden/,'La vista completa de configuración comienza oculta');
assert.match(js,/function isAdmin\(\)\{return state\.actor\?\.supervisor===true;\}/,'El acceso administrativo requiere un valor booleano explícito');
assert.match(js,/function adminActionsMarkup\(r\)[\s\S]*Reabrir o corregir entrega[\s\S]*Retroceder o corregir estado[\s\S]*Eliminar reserva/,'El administrador debe tener acciones visibles para reabrir, retroceder y eliminar');
assert.match(js,/function actionDelete\(\)\{if\(!isAdmin\(\)\)/,'La interfaz debe bloquear la eliminación para usuarios no administradores');
assert.match(js,/function actionCorrectClose\(\)\{if\(!isAdmin\(\)\)/,'La interfaz debe bloquear la reapertura para usuarios no administradores');
assert.match(js,/if\(view==='settings'&&!isAdmin\(\)\)view='active'/,'Un usuario sin permisos no puede abrir la vista administrativa');
assert.match(js,/function splitItem\(index\)[\s\S]*state\.newItems\.splice/,'Un mismo producto se puede dividir entre orígenes');
assert.match(js,/Situación física \*[\s\S]*Está en el local, falta separarlo[\s\S]*Ya está separado para esta reserva[\s\S]*Está separado parcialmente/,'Cada producto disponible debe declarar su situación física');
assert.match(js,/missingSeparation[\s\S]*Indicá si \$\{missingSeparation\.nombre\} ya quedó separado físicamente/,'La creación debe impedir que se omita la situación física de un producto local');
assert.match(js,/data-item-field="procedencia"[\s\S]*data-item-field="proveedor_nombre"[\s\S]*data-item-field="origen_local"[\s\S]*data-item-field="pedido_local_gestion"/,'Cada línea captura proveedor o gestión entre locales');
assert.match(js,/const transportLabels=[\s\S]*Próxima reposición[\s\S]*Agencia o transporte tercero[\s\S]*Traslado propio[\s\S]*data-item-field="traslado_tipo"/,'Cada producto pedido a otro local define cómo viajará');
assert.match(js,/data-item-field="cantidad_origen"/,'La coordinación externa distingue lo separado en origen');
assert.match(js,/op_reserva_pedidos_candidatos/,'La creación puede elegir un pedido existente sin duplicarlo');
assert.match(js,/op_reserva_editar/,'La reserva completa se puede editar antes de entregas');
assert.match(js,/op_reserva_eliminar/,'Una carga errónea se puede eliminar con confirmación');
assert.match(js,/op_reserva_corregir_cierre/,'Los administradores deben poder corregir un cierre o una entrega errónea');
assert.match(js,/Se restaurarán las cantidades que estaban separadas antes de cancelar/,'La corrección de cancelación debe explicar que restaura la mercadería');
assert.match(js,/returned\?x\.dataset\.current:x\.dataset\.withLocal/,'No retirado no debe sumar la mercadería local como si hubiera sido entregada');
assert.match(js,/volverán a exhibición\. No se modifica stock/,'La interfaz debe explicar el efecto de no retirado');
assert.match(js,/@page\{size:80mm 200mm;margin:0\}[\s\S]*width:80mm;height:200mm[\s\S]*width:199mm;height:79mm[\s\S]*transform:rotate\(90deg\)[\s\S]*grid-template-columns:66mm/,'La etiqueta horizontal se rota dentro de una única hoja física de 80 por 200 mm');
assert.match(js,/function reservationNumber\(r\)[\s\S]*r\?\.numero\?\?r\?\.number/,'La interfaz debe priorizar el número consecutivo de la reserva');
assert.match(js,/class="phone">TEL: \$\{html\(phone\)\}/,'La etiqueta debe imprimir el teléfono del cliente');
assert.doesNotMatch(js,/class="reason">\$\{html\(r\.motivo_nombre\)\}/,'La etiqueta no debe imprimir el motivo');
assert.match(js,/@page\{size:80mm 116mm;margin:0\}[\s\S]*width:72mm;height:100\.1mm/,'La plantilla de calibración respeta 576 por 800 puntos a 203 dpi');
assert.match(js,/ESCALA 100 % · SIN MÁRGENES · SIN AJUSTAR/,'La prueba incluye las instrucciones críticas del controlador');
assert.match(js,/UBICACIÓN: \$\{html\(location\)\}/,'La etiqueta debe indicar el lugar configurado para encontrar la mercadería');
assert.match(js,/p_ubicacion:location\|\|null/,'La ubicación se guarda junto con la configuración del local');
assert.match(js,/p_horas:48/,'La interfaz debe guardar siempre la política de 48 horas exactas');
assert.match(js,/Días habituales de recepción desde \$\{origin\}[\s\S]*fecha estimada es opcional/,'Los calendarios por origen deben orientar sin imponer la fecha estimada');
assert.match(js,/Ayuda de reservas[\s\S]*Definir el destino[\s\S]*Disponible en el local[\s\S]*Pedido a otro local[\s\S]*Separado en origen no es recibido/,'La ayuda debe explicar los procesos distintos con lenguaje operativo');
assert.match(js,/state\.publicCreate\?'':'<div class="guide-step"><strong>Completar el proceso/,'El seguimiento se explica únicamente dentro de la aplicación autenticada');
assert.doesNotMatch(js,/El remito es[\s\S]*no un motivo|WhatsApp o llamada/,'La ayuda no debe reproducir aclaraciones del proceso de desarrollo');
assert.match(js,/actionCreated\(result,state\.current\.items\.some\(item=>item\.cantidad_local>0\)\)/,'La creación debe distinguir si ya hay mercadería física para etiquetar');
assert.match(js,/function actionCreated\(result,hasLocalStock\)[\s\S]*etiqueta ya se puede imprimir[\s\S]*Continuar sin imprimir/,'La creación debe ofrecer la etiqueta aunque todavía falte mercadería');
assert.match(js,/Enlace de seguimiento[\s\S]*data-copy-created-link/,'La confirmación debe mostrar y permitir copiar el mismo enlace del QR');
assert.match(js,/function trackingUrl\(token\)\{return `\$\{location\.origin\}\/reserva#/,'El enlace copiable debe coincidir con el destino impreso en el QR');
assert.match(js,/const arrived=qty>item\.cantidad_local[\s\S]*if\(arrived\)actionMerchandiseArrived/,'Al registrar una llegada debe recordarse colocar la etiqueta');
assert.match(js,/function actionPrintPrompt[\s\S]*Imprimir etiqueta/,'Cuando hay mercadería física debe ofrecerse la impresión inmediata');
assert.match(js,/function printShortcutMarkup\(\)[\s\S]*Imprimila cuando necesites identificar la mercadería[\s\S]*unidades disponibles y las pendientes/,'El detalle debe mantener siempre visible la impresión del QR');
assert.match(js,/Situación física \*[\s\S]*Cantidad reservada/,'La creación debe distinguir cantidad reservada y situación física');
assert.match(js,/Ya está separado para esta reserva:[\s\S]*No necesita fecha estimada ni remito/,'Un producto ya separado no debe pedir datos de una llegada futura');
assert.match(js,/Unidades separadas aquí[\s\S]*local de destino[\s\S]*Solicitadas[\s\S]*Ya entregadas/,'El detalle debe explicar las cantidades operativas');
assert.match(js,/function itemProcessMarkup[\s\S]*separadas en origen[\s\S]*recibidas aquí/,'El detalle debe diferenciar preparación en origen y recepción en destino');
assert.match(js,/function nextStep\(r,items\)[\s\S]*data-next-step/,'Cada estado debe mostrar una única acción siguiente y comprensible');
assert.match(js,/Separar la mercadería disponible en el local[\s\S]*Registrar separación[\s\S]*Actualizar separaciones y llegadas[\s\S]*Actualizar cantidades/,'El siguiente paso debe distinguir separación local de llegada externa');
for(const label of ['Registrar llegada y separación','Confirmar que el cliente fue avisado','Registrar entrega o cierre'])assert.ok(js.includes(label),`Falta la acción guiada: ${label}`);
assert.match(js,/Estado del traslado[\s\S]*preparado_origen[\s\S]*en_transito/,'Los pedidos gestionados por fuera pueden registrar preparación y despacho por producto');
assert.match(js,/function actionRegisterArrival\(\)[\s\S]*No cuentes mercadería que siga en góndola o depósito general[\s\S]*estado avanzará automáticamente/,'La llegada guiada debe evitar separar mercadería solo de palabra');
assert.match(js,/data-print-created[\s\S]*return printLabel\(\)/,'La acción posterior a la creación debe iniciar la impresión');
assert.match(js,/async function printLabel\(\)[\s\S]*window\.open[\s\S]*await renderPrintWindow\(r,trackingUrl\(token\),win\)/,'La etiqueta debe reservar su ventana antes de esperar la generación del QR');
assert.match(js,/async function renderPrintWindow\(r,url,win\)/,'La impresión debe reutilizar la ventana abierta por el gesto del empleado');
assert.match(js,/renderPrintWindow\(r,url,win\)[\s\S]*MOTIVO: \$\{html\(reason\)\}[\s\S]*OBSERVACIONES: \$\{html\(observations\)\}/,'La etiqueta interna debe incluir el motivo y las observaciones de la reserva');
assert.doesNotMatch(js,/SUCAN · CONTROL DE RESERVAS/,'La etiqueta interna no debe mostrar la firma anterior');
assert.match(js,/SucaneitorSearch\?\.createSearchIndex|window\.SucaneitorSearch\?\.createSearchIndex/,'El padrón de reservas debe usar el índice del buscador de inventario');
assert.match(js,/S\.rankProducts\(index,q,null,limit\)[\s\S]*S\.searchByCode\(index,q,limit\)/,'La búsqueda por nombre y código debe compartir el ordenamiento del conteo');
assert.match(js,/fetch\('\/products\.json',[\s\S]*debounce\(\(\)=>\{if\(state\.productSearchType!==\'barras\'\)searchProducts\(\);\},90\)/,'La búsqueda debe usar el padrón completo y responder con la misma demora rápida del conteo');
assert.match(js,/function startRealtimeFallback\(error\)[\s\S]*setInterval\(refreshVisibleReservationData,15000\)/,'Si iOS bloquea WebSocket, las reservas deben seguir actualizándose por sondeo');
assert.match(js,/hadContent=listEl\.dataset\.loaded==='true'[\s\S]*signature!==state\.listSignatures\[kind\]/,'La actualización periódica debe conservar las tarjetas y evitar reemplazos sin cambios');
assert.match(js,/openDetail\(state\.current\.reservation\.id,\{silent:true\}\)/,'El detalle abierto debe refrescarse sin mostrar una pantalla de carga');
assert.match(js,/channel\.subscribe\(status=>[\s\S]*startRealtimeFallback\(error\)/,'Un fallo al abrir Realtime no debe impedir entrar al módulo');
assert.match(page,/reservas\.css\?v=8[\s\S]*search-engine\.js\?v=search-fast-v6[\s\S]*reserva-engine\.js\?v=3[\s\S]*reservas\.js\?v=16/,'El enlace posterior a la creación debe invalidar la caché anterior');
assert.match(lookupPage,/consulta\.css\?v=3[\s\S]*qrcodejs@1\.0\.0[\s\S]*reserva-engine\.js\?v=3[\s\S]*consulta\.js\?v=8/,'La reimpresión pública debe cargar el generador QR e invalidar la caché');
assert.match(lookup,/number=r\.number\?\?r\.code/,'La consulta QR debe mostrar el número consecutivo cuando existe');
assert.match(lookupPage,/Motivo y observaciones generales[\s\S]*id="lookup-purpose"[\s\S]*id="lookup-observations"/,'El QR debe reservar un espacio visible para el motivo y las observaciones generales');
assert.match(lookup,/\$\('lookup-purpose'\)\.textContent=[\s\S]*\$\('lookup-observations'\)\.textContent=r\.observations/,'La consulta QR debe completar el motivo y las observaciones recibidas');
assert.match(lookupPage,/id="lookup-print"[^>]*>Imprimir etiqueta/,'El enlace público debe ofrecer la reimpresión de la etiqueta');
assert.match(lookup,/async function printLabel\(r\)[\s\S]*qrDataUrl\(trackingUrl\(\)\)[\s\S]*TEL: \$\{html\(phone\)\}/,'La reimpresión pública debe reutilizar el enlace y los datos completos de la etiqueta');
assert.match(lookup,/printLabel\(r\)[\s\S]*r\.observations[\s\S]*MOTIVO: \$\{html\(reason\)\}[\s\S]*OBSERVACIONES: \$\{html\(observations\)\}/,'La reimpresión pública debe conservar motivo y observaciones');
assert.doesNotMatch(lookup,/SUCAN · CONTROL DE RESERVAS/,'La reimpresión pública no debe mostrar la firma anterior');
assert.match(lookup,/const itemOrigin=i=>[\s\S]*proveedor_nombre[\s\S]*origen_local[\s\S]*pedido_local_gestion/,'El QR público explica el origen específico de cada producto');
assert.match(js,/async function printCalibration\(\)[\s\S]*window\.open[\s\S]*await qrDataUrl/,'La calibración debe abrir su ventana antes de generar el QR');
assert.match(js,/\/reserva#/,'La etiqueta abre una consulta de solo lectura');
assert.match(receipt,/receiptReservationData/,'Recepción muestra reservas coincidentes');
assert.match(receipt,/op_recepcion_confirmar_reserva/,'Recepción permite confirmar la vinculación');
assert.match(rootJs,/op_agenda_guardar_cliente/,'La agenda debe guardar mediante la deduplicación central por teléfono');
assert.match(css,/@media\(max-width:780px\)/,'El módulo incluye interfaz móvil');
console.log('reservations ui contract ok');
