const fs=require('fs'),assert=require('assert');
const sql=fs.readFileSync('supabase/migrations/20260909010000_control_reservas.sql','utf8'),changes=fs.readFileSync('supabase/migrations/20260910010000_reservas_edicion_eliminacion.sql','utf8'),unaccentFix=fs.readFileSync('supabase/migrations/20260910020000_reservas_unaccent_listado.sql','utf8'),itemOrigins=fs.readFileSync('supabase/migrations/20260910030000_reservas_origen_por_producto.sql','utf8');
for(const table of ['op_reservas','op_reserva_items','op_reserva_motivos','op_reserva_comentarios','op_reserva_eventos','op_reserva_enlaces','op_reserva_invitados','op_recepcion_reservas'])assert.match(sql,new RegExp(`create table if not exists public\\.${table}\\b`),`Falta ${table}`);
for(const fn of ['op_reserva_crear','op_reserva_listar','op_reserva_detalle','op_reserva_actualizar_item','op_reserva_pedidos_disponibles','op_reserva_vincular_pedido','op_reserva_cambiar_estado','op_reserva_finalizar','op_reserva_cancelar','op_reserva_corregir_cierre','op_reserva_excepcion','op_reserva_qr_detalle','op_reserva_invitado_entrar','op_recepcion_reservas_datos','op_recepcion_confirmar_reserva','op_agenda_guardar_cliente'])assert.match(sql,new RegExp(`function public\\.${fn}\\(`),`Falta ${fn}`);
assert.match(sql,/make_interval\(hours=>v_horas\)/,'El vencimiento debe usar las horas configuradas');
assert.match(sql,/constraint op_reserva_config_horas_check check \(horas_reserva=48\)/,'La política debe quedar fijada en 48 horas exactas');
assert.match(sql,/estado_antes_vencido=estado,estado='vencido'/,'Debe conservar el estado al vencer');
assert.match(sql,/select p\.id,'Reserva vencida'[\s\S]+from vencidas v join public\.perfiles p on p\.approved=true\s*\n/,'El vencimiento debe avisar a todos los empleados aprobados');
assert.match(sql,/estado=restaurar,estado_antes_vencido=null,excepcion_hasta=p_hasta/,'La excepción debe restaurar el proceso');
assert.match(sql,/insert into public\.pedidos[\s\S]+reserva_id/,'La reserva debe crear pedidos entre locales vinculados');
assert.match(sql,/op_reserva_sync_pedido_estado/,'Pedidos y reposición deben sincronizar la reserva');
assert.match(sql,/op_reserva_sync_recepcion_cierre/,'El cierre del remito debe sincronizar reservas');
assert.match(sql,/cron\.schedule\([\s\S]*control-reservas-vencimientos[\s\S]*op_reservas_actualizar_vencidas/,'El vencimiento debe ejecutarse automáticamente aunque nadie tenga el módulo abierto');
assert.match(sql,/cantidad_local \+ cantidad_entregada <= cantidad/,'Una entrega parcial no debe permitir volver a contar unidades ya entregadas');
assert.match(sql,/set qr_token=v_token,qr_token_hash=/,'El QR impreso debe quedar asociado de forma estable a la reserva');
assert.match(sql,/token:=r\.qr_token;[\s\S]*if token is null then/,'Reimprimir no debe invalidar etiquetas anteriores');
assert.match(sql,/function public\.op_reserva_corregir_cierre[\s\S]*cantidad_local=least\(cantidad-nueva,cantidad_local\+devueltas\)/,'Deshacer una entrega debe devolver las unidades al seguimiento local');
assert.match(sql,/if r\.estado in \('completado','cancelado'\) then raise exception 'La reserva está cerrada; usá Corregir cierre'/,'Una reserva cerrada solo debe reabrirse mediante la acción auditada');
assert.match(sql,/if p_tipo='no_retirado'[\s\S]*cantidad_local=0,estado=case when cantidad_entregada>=cantidad then 'entregado' else 'pendiente' end/,'No retirado debe liberar lo pendiente sin registrarlo como entregado');
assert.match(sql,/detalle->'productos_locales'[\s\S]*accion='cancelar'[\s\S]*jsonb_array_elements\(cancelados\)/,'Deshacer una cancelación debe restaurar la mercadería separada desde la auditoría');
assert.match(sql,/cantidad_local=least\(i\.cantidad-i\.cantidad_entregada,i\.cantidad_local\+a\.cantidad\)/,'Una recepción no debe volver a separar unidades ya entregadas');
assert.match(sql,/clientes_agenda alter column nombre drop not null/,'Los datos del cliente deben seguir siendo opcionales también en la agenda');
assert.match(sql,/pg_advisory_xact_lock\(hashtext\('agenda:'\|\|v_phone\)\)/,'La agenda debe serializar la deduplicación por teléfono');
assert.match(sql,/'ubicacion_reservas',ubicacion_reservas/,'La configuración debe exponer el lugar fijo de reservas de cada tienda');
assert.match(sql,/grant execute on function public\.op_reserva_guardar_config\(text,integer,smallint\[\],text,text,text\) to authenticated/,'Solo usuarios autenticados pueden cambiar la configuración del local');
assert.match(sql,/alter table public\.op_reservas enable row level security/,'Reservas debe usar RLS');
assert.match(sql,/grant execute on function public\.op_reserva_qr_detalle\(text\) to anon,authenticated/,'El QR de solo lectura debe ser público');
assert.doesNotMatch(sql,/grant (?:all|select|insert|update|delete)[^;]+op_reservas[^;]+to anon/i,'Anónimos no deben acceder directamente a las tablas');
assert.match(sql,/char_length\(trim\(coalesce\(p_motivo,''\)\)\) not between 3 and 500/,'Cancelar o exceptuar requiere motivo');
assert.match(changes,/\('Pedido a otro local',10\)[\s\S]*\('Esperando proveedor',20\)[\s\S]*\('Ya estaba en local',30\)/,'Los tres motivos operativos se configuran para todos los locales');
assert.match(changes,/pedido_local_gestion in \('crear','existente','externo'\)/,'La forma de gestionar un pedido entre locales queda registrada');
for(const fn of ['op_reserva_crear_v2','op_reserva_pedidos_candidatos','op_reserva_editar','op_reserva_eliminar'])assert.match(changes,new RegExp(`function public\\.${fn}\\(`),`Falta ${fn}`);
assert.match(changes,/generado_desde_reserva and estado='pendiente'/,'Solo se eliminan pedidos generados por Reservas que todavía no avanzaron');
assert.match(changes,/create table if not exists public\.op_reserva_eliminaciones/,'Las eliminaciones conservan una copia de auditoría');
assert.match(changes,/cantidad_entregada>0[\s\S]*no se puede eliminar/,'Una reserva con entregas no se puede borrar');
assert.match(changes,/gestion='existente'[\s\S]*op_reserva_vincular_pedido/,'Un pedido ya creado se vincula en vez de duplicarse');
assert.match(unaccentFix,/alter function public\.op_reserva_listar\(jsonb,text\)[\s\S]*search_path\s*=\s*public,\s*extensions,\s*pg_temp/,'El listado debe poder resolver unaccent en producción');
assert.match(itemOrigins,/add column if not exists proveedor_nombre[\s\S]*add column if not exists pedido_local_gestion/,'Proveedor y gestión entre locales se guardan por producto');
assert.match(itemOrigins,/create table if not exists public\.op_reserva_recepciones_habituales[\s\S]*origen_tipo in \('proveedor','local'\)[\s\S]*dias_recepcion/,'Los calendarios distinguen proveedor y local de origen');
assert.match(itemOrigins,/Solo administradores pueden configurar calendarios de recepción/,'Solo administradores pueden cambiar calendarios');
assert.match(itemOrigins,/'reception_schedules',recepciones/,'El contexto expone calendarios al formulario');
assert.match(itemOrigins,/count\(distinct x->>'procedencia'\)>1 then 'Origen mixto'/,'El encabezado se deriva de los orígenes de las líneas');
assert.match(itemOrigins,/pedido_local_gestion='crear'[\s\S]*insert into public\.pedidos/,'Solo las líneas configuradas para crear generan pedidos entre locales');
assert.match(itemOrigins,/pedido_local_gestion'='existente'[\s\S]*pedido_existente_id/,'Cada línea puede vincular su propio pedido existente');
console.log('reservations sql contract ok');
