const fs=require('fs'),assert=require('assert');
const page=fs.readFileSync('reservas/index.html','utf8'),js=fs.readFileSync('reservas/reservas.js','utf8'),css=fs.readFileSync('reservas/reservas.css','utf8'),lookupPage=fs.readFileSync('reserva.html','utf8'),lookup=fs.readFileSync('reservas/consulta.js','utf8'),root=fs.readFileSync('index.html','utf8'),rootJs=fs.readFileSync('app.js','utf8'),receipt=fs.readFileSync('operaciones/receipt-orders.js','utf8');
assert.match(root,/href="\/reservas"[\s\S]+Control de reservas/,'El inicio debe mostrar el módulo');
assert.match(page,/id="access-key"/,'El acceso rápido pide contraseña de empresa');
assert.match(page,/id="access-name"/,'El acceso rápido registra al empleado');
assert.match(page,/id="guide-button"/,'El módulo debe ofrecer instrucciones operativas sin salir del flujo');
assert.doesNotMatch(page,/id="new-reason"/,'La creación no debe imponer un único motivo general');
assert.match(page,/Pedido a otro local[\s\S]*Esperando proveedor[\s\S]*Ya estaba en local/,'La configuración explica los tres motivos operativos');
assert.match(page,/Productos y origen[\s\S]*Cada producto puede estar en el local[\s\S]*Dividir origen/,'La creación explica el origen independiente y la división de cantidades');
assert.match(page,/id="new-responsible"/,'La creación pide responsable');
assert.match(page,/id="schedule-type"[\s\S]*value="proveedor"[\s\S]*value="local"[\s\S]*schedule-days/,'El administrador configura calendarios por proveedor o local de origen');
assert.match(page,/id="customer-document"/,'Los datos opcionales incluyen documento');
assert.match(page,/data-view="history"/,'Existe historial');
assert.match(page,/id="settings-printer"/,'La ruta de impresora es configurable');
assert.match(page,/id="settings-location"/,'El lugar fijo de las reservas debe poder configurarse por tienda');
assert.doesNotMatch(page,/id="settings-hours"/,'El plazo exacto de 48 horas no debe ser editable');
assert.match(page,/id="print-calibration"/,'La configuración debe ofrecer la prueba física de la BSC10');
assert.match(page,/jsbarcode@3\.12\.3/,'La calibración usa un Code 128 real y una versión fijada');
assert.match(js,/op_reserva_invitado_entrar/,'El acceso rápido usa una sesión limitada');
assert.match(js,/responsable:responsible/,'La creación debe enviar el nombre del responsable sin provocar un error de variable');
assert.match(js,/const sourceLabels=\{local:'Ya estaba en el local',proveedor:'Esperando proveedor',pedido_local:'Pedido a otro local'\}/,'La interfaz ofrece los tres orígenes en cada producto');
assert.match(js,/function splitItem\(index\)[\s\S]*state\.newItems\.splice/,'Un mismo producto se puede dividir entre orígenes');
assert.match(js,/data-item-field="procedencia"[\s\S]*data-item-field="proveedor_nombre"[\s\S]*data-item-field="origen_local"[\s\S]*data-item-field="pedido_local_gestion"/,'Cada línea captura proveedor o gestión entre locales');
assert.match(js,/op_reserva_pedidos_candidatos/,'La creación puede elegir un pedido existente sin duplicarlo');
assert.match(js,/op_reserva_editar/,'La reserva completa se puede editar antes de entregas');
assert.match(js,/op_reserva_eliminar/,'Una carga errónea se puede eliminar con confirmación');
assert.match(js,/op_reserva_corregir_cierre/,'Los empleados deben poder corregir un cierre o una entrega errónea');
assert.match(js,/Se restaurarán las cantidades que estaban separadas antes de cancelar/,'La corrección de cancelación debe explicar que restaura la mercadería');
assert.match(js,/returned\?x\.dataset\.current:x\.dataset\.withLocal/,'No retirado no debe sumar la mercadería local como si hubiera sido entregada');
assert.match(js,/volverán a exhibición\. No se modifica stock/,'La interfaz debe explicar el efecto de no retirado');
assert.match(js,/@page\{size:80mm 200mm;margin:0\}[\s\S]*width:80mm;height:200mm[\s\S]*width:199mm;height:79mm[\s\S]*transform:rotate\(90deg\)[\s\S]*grid-template-columns:66mm/,'La etiqueta horizontal se rota dentro de una única hoja física de 80 por 200 mm');
assert.match(js,/@page\{size:80mm 116mm;margin:0\}[\s\S]*width:72mm;height:100\.1mm/,'La plantilla de calibración respeta 576 por 800 puntos a 203 dpi');
assert.match(js,/ESCALA 100 % · SIN MÁRGENES · SIN AJUSTAR/,'La prueba incluye las instrucciones críticas del controlador');
assert.match(js,/UBICACIÓN: \$\{html\(location\)\}/,'La etiqueta debe indicar el lugar configurado para encontrar la mercadería');
assert.match(js,/p_ubicacion:location\|\|null/,'La ubicación se guarda junto con la configuración del local');
assert.match(js,/p_horas:48/,'La interfaz debe guardar siempre la política de 48 horas exactas');
assert.match(js,/Recepción habitual desde \$\{origin\}[\s\S]*Podés indicar otra fecha/,'Los calendarios por origen deben orientar sin imponer la fecha estimada');
assert.match(js,/Cómo usar Control de reservas[\s\S]*Dividir cantidades cuando corresponda[\s\S]*Resolver cada pedido entre locales[\s\S]*Editar o corregir[\s\S]*Cerrar siempre/,'La guía debe cubrir orígenes por producto y correcciones auditadas');
assert.match(js,/actionCreated\(result,state\.current\.items\.some\(item=>item\.cantidad_local>0\)\)/,'La creación debe distinguir si ya hay mercadería física para etiquetar');
assert.match(js,/function actionCreated\(result,hasLocalStock\)[\s\S]*podés imprimir la etiqueta desde ahora[\s\S]*Continuar sin imprimir/,'La creación debe ofrecer la etiqueta aunque todavía falte mercadería');
assert.match(js,/const arrived=qty>item\.cantidad_local[\s\S]*if\(arrived\)actionMerchandiseArrived/,'Al registrar una llegada debe recordarse colocar la etiqueta');
assert.match(js,/function actionPrintPrompt[\s\S]*Imprimir etiqueta ahora/,'Cuando hay mercadería física debe ofrecerse la impresión inmediata');
assert.match(js,/function printShortcutMarkup\(\)[\s\S]*Podés imprimirla en cualquier momento[\s\S]*qué productos llegaron y cuáles faltan/,'El detalle debe mantener siempre visible la impresión del QR');
assert.match(js,/Unidades separadas aquí[\s\S]*Solo las que están físicamente juntas para esta reserva[\s\S]*Solicitadas[\s\S]*Ya entregadas/,'Las cantidades de cada producto deben explicar su significado operativo');
assert.match(js,/function nextStep\(r,items\)[\s\S]*data-next-step/,'Cada estado debe mostrar una única acción siguiente y comprensible');
for(const label of ['Registrar llegada y separación','Confirmar que el cliente fue avisado','Registrar entrega o cierre'])assert.ok(js.includes(label),`Falta la acción guiada: ${label}`);
assert.match(js,/data-mark-transit[\s\S]*function markItemTransit/,'Los pedidos gestionados por fuera pueden avanzar por producto');
assert.match(js,/function actionRegisterArrival\(\)[\s\S]*No cuentes mercadería que siga en góndola o depósito general[\s\S]*estado avanzará automáticamente/,'La llegada guiada debe evitar separar mercadería solo de palabra');
assert.match(js,/data-print-created[\s\S]*return printLabel\(\)/,'La acción posterior a la creación debe iniciar la impresión');
assert.match(js,/async function printLabel\(\)[\s\S]*window\.open[\s\S]*await renderPrintWindow\(r,url,win\)/,'La etiqueta debe reservar su ventana antes de esperar la generación del QR');
assert.match(js,/async function renderPrintWindow\(r,url,win\)/,'La impresión debe reutilizar la ventana abierta por el gesto del empleado');
assert.match(js,/function startRealtimeFallback\(error\)[\s\S]*setInterval\(refreshVisibleReservationData,15000\)/,'Si iOS bloquea WebSocket, las reservas deben seguir actualizándose por sondeo');
assert.match(js,/hadContent=listEl\.dataset\.loaded==='true'[\s\S]*signature!==state\.listSignatures\[kind\]/,'La actualización periódica debe conservar las tarjetas y evitar reemplazos sin cambios');
assert.match(js,/openDetail\(state\.current\.reservation\.id,\{silent:true\}\)/,'El detalle abierto debe refrescarse sin mostrar una pantalla de carga');
assert.match(js,/channel\.subscribe\(status=>[\s\S]*startRealtimeFallback\(error\)/,'Un fallo al abrir Realtime no debe impedir entrar al módulo');
assert.match(page,/reservas\.css\?v=5[\s\S]*reservas\.js\?v=7/,'El origen por producto debe invalidar la caché anterior');
assert.match(lookupPage,/consulta\.js\?v=2/,'La consulta QR debe invalidar su caché anterior');
assert.match(lookup,/const itemOrigin=i=>[\s\S]*proveedor_nombre[\s\S]*origen_local[\s\S]*pedido_local_gestion/,'El QR público explica el origen específico de cada producto');
assert.match(js,/async function printCalibration\(\)[\s\S]*window\.open[\s\S]*await qrDataUrl/,'La calibración debe abrir su ventana antes de generar el QR');
assert.match(js,/\/reserva#/,'La etiqueta abre una consulta de solo lectura');
assert.match(receipt,/receiptReservationData/,'Recepción muestra reservas coincidentes');
assert.match(receipt,/op_recepcion_confirmar_reserva/,'Recepción permite confirmar la vinculación');
assert.match(rootJs,/op_agenda_guardar_cliente/,'La agenda debe guardar mediante la deduplicación central por teléfono');
assert.match(css,/@media\(max-width:780px\)/,'El módulo incluye interfaz móvil');
console.log('reservations ui contract ok');
