const assert=require('node:assert/strict'),{randomUUID:uuid}=require('node:crypto');
const {createDatabase}=require('./postgres-test-setup');
async function main(){
 const db=await createDatabase(),q=async(sql,args=[])=> (await db.query(sql,args)).rows;
 const scalar=async(sql,args=[])=>Object.values((await q(sql,args))[0])[0];
 const origin=uuid(),other=uuid(),supervisor=uuid(),pending=uuid(),blankLocal=uuid();
 for(const [id,name,local,role,approved] of [[origin,'María Pérez','Punta del Este','empleado',true],[other,'Usuario ajeno','Colonia','empleado',true],[supervisor,'Supervisión','Maldonado','supervisor_general',true],[pending,'Sin aprobar','Punta del Este','empleado',false],[blankLocal,'Sin local','','empleado',true]]){
  await q('insert into auth.users(id) values($1)',[id]);await q('insert into perfiles(id,nombre,apellido,local_nombre,almacen,role,approved) values($1,$2,$3,$4,$5,$6,$7)',[id,name,'Prueba',local,'TEST',role,approved]);
 }
 const repo=uuid(),privateRepo=uuid(),inv=uuid(),rec=uuid(),guest=uuid(),invitation=uuid();
 await q("update locales set almacen='PDE' where nombre='Punta del Este'");
 await q("insert into op_reposiciones(id,nombre,origen_local,destino_local,created_by,created_at,updated_at) values($1,'Reposición histórica prueba','Punta del Este','Maldonado',$2,'2020-01-02T01:00:00Z','2020-01-03T12:00:00Z')",[repo,origin]);
 await q("insert into op_reposiciones(id,nombre,origen_local,destino_local,created_by) values($1,'Privada','Colonia','Salto',$2)",[privateRepo,other]);
 await q("insert into op_reposicion_items(reposicion_id,codigo,nombre,barras,pedido_reposicion,preparado,stock_origen) values($1,'A','Snack perro','001234',4,1,0),($1,'B','Arena sanitaria','005678',3,3,20),($2,'SECRET','Producto ajeno','00999',1,0,9)",[repo,privateRepo]);
 await q("insert into op_reposicion_extras(reposicion_id,codigo,nombre,cantidad) values($1,'X','Juguete extra',2)",[repo]);
 await q("insert into productos(codigo,nombre,barras,marca) values('A','Snack perro nuevo','008888','Marca Uno')");
 await q("insert into op_invitaciones_sesion(id,modulo,sesion_id,token_hash,created_by) values($1,'reposicion',$2,'NOT-A-TOKEN',$3)",[invitation,repo,origin]);
 await q("insert into op_invitados_sesion(id,invitacion_id,modulo,sesion_id,nombre,access_hash,dispositivo_id,cliente_id,revoked_at) values($1,$2,'reposicion',$3,'José invitado','PRIVATE-ACCESS','device-test-01','guest-test-01',now())",[guest,invitation,repo]);
 await q("insert into op_inventario_sesiones(id,nombre,local_nombre,created_by,estado) values($1,'Inventario histórico','Punta del Este',$2,'cerrada')",[inv,origin]);
 await q("insert into op_inventario_items(sesion_id,codigo,nombre,cantidad) values($1,'A','Snack perro',2),($1,'N','Producto sin balance',0)",[inv]);
 await q("insert into op_inventario_balances(sesion_id,balance) values($1,$2::jsonb)",[inv,JSON.stringify([{codigo:'A',nombre:'Snack perro',stockActual:5},{codigo:'B',nombre:'Arena sanitaria',stockActual:0},{codigo:'C',nombre:'Ración perro',stockActual:-1}])]);
 await q("insert into op_recepciones(id,nombre,numero_remito,fecha_remito,origen_local,destino_local,created_by) values($1,'Control prueba','R-777','2024-02-20','Maldonado','Punta del Este',$2)",[rec,origin]);
 await q("insert into op_recepcion_items(recepcion_id,codigo,nombre,esperado,recibido) values($1,'A','Snack perro',4,1)",[rec]);
 const login=async(id=origin,role='authenticated')=>{await db.exec('reset role');await q("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);await db.exec('set role '+role);};
 const search=(module='reposicion',filters={},page=0,limit=24)=>scalar('select op_buscar_sesiones($1,$2::jsonb,$3,$4)',[module,JSON.stringify(filters),page,limit]);
 let checks=0;const eq=(a,b,msg)=>{assert.deepEqual(a,b,msg);checks++;};const fails=async(fn,re)=>{await assert.rejects(fn,re);checks++;};
 await login();
 let result=await search();eq(result.total,1,'Old sessions included beyond 90 days');eq(result.sessions[0].id,repo);eq(result.sessions[0].summary.quantity,6);eq(result.sessions[0].summary.products,2);eq(result.sessions[0].summary.extras,1);
 eq(result.facets.locals.includes('Colonia'),false,'No unrelated local facet');eq(result.facets.users.some(p=>p.id==='user:'+other),false,'No unrelated person facet');
 eq((await search('reposicion',{query:'historica maria PDE'})).total,1,'Combined accents, creator and alias');
 for(const term of ['001234','008888','Marca Uno','Snack perro nuevo'])eq((await search('reposicion',{product:term})).total,1,'Stored and current catalog identifiers');
 eq((await search('reposicion',{product:'A',stock:'positive',categories:['snacks']})).total,0,'Product/category/stock must match the same item');
 eq((await search('reposicion',{product:'Snack',stock:'zero',categories:['snacks']})).total,1);
 eq((await search('reposicion',{product:'Snack',stock_min:'1'})).total,0);eq((await search('reposicion',{stock_min:'10',stock_max:'30'})).total,1);
 eq((await search('reposicion',{product:'Juguete',stock:'unknown'})).total,1,'Extras have unknown stock, not zero');
 eq((await search('reposicion',{product:'Juguete',stock:'zero'})).total,0);
 eq((await search('reposicion',{user:'guest:'+guest})).total,1,'Historical QR participation remains searchable after revocation');
 eq((await search('reposicion',{origin:'Maldonado'})).total,0,'Origin is directional');
 eq((await search('reposicion',{local:'Maldonado'})).total,1);
 eq((await search('reposicion',{date_from:'2020-01-01',date_to:'2020-01-01'})).total,1,'Uruguay timezone day boundaries');
 eq((await search('reposicion',{date_from:'2020-01-02'})).total,0);
 eq((await search('reposicion',{date_field:'updated',date_from:'2020-01-03',date_to:'2020-01-03'})).total,1);
 eq((await search('reposicion',{states:['preparando','enviado']})).total,1);eq((await search('reposicion',{states:['enviado']})).total,0);
 eq((await search('reposicion',{product:'Snack',quantity:'shortage'})).total,1);eq((await search('reposicion',{product:'Arena',quantity:'exact'})).total,1);
 eq((await search('inventario')).sessions[0].can_edit,false,'Closed inventory is read only');
 eq((await search('inventario',{product:'Arena',quantity:'pending',stock:'zero'})).total,1,'Uncounted balance product remains distinguishable from zero counted');
 eq((await search('inventario',{product:'Snack',quantity:'shortage'})).total,1);
 eq((await search('inventario',{stock:'negative'})).total,1);
 eq((await search('inventario',{product:'sin balance',stock:'unknown'})).total,1);
 eq((await search('recepcion',{query:'R-777',date_field:'document',date_from:'2024-02-20',date_to:'2024-02-20'})).total,1);
 eq((await search('recepcion',{stock:'zero'})).total,0,'Receipts are not stock on hand');
 eq((await search('reposicion',{query:"' OR 1=1 --"})).total,0,'Search is not executable SQL');
 await fails(()=>search('reposicion',{date_from:'2025-01-01',date_to:'2020-01-01'}),/fecha inicial/);
 await fails(()=>search('reposicion',{stock_min:'20',stock_max:'1'}),/stock mínimo/);
 await fails(()=>search('reposicion',{states:'preparando'}),/Estados/);
 await fails(()=>search('other'),/Módulo/);
 const detail=await scalar("select op_consultar_productos_sesion('reposicion',$1,'Snack')",[repo]);
 eq(detail.total,1);eq(detail.products[0].stock,0);eq(JSON.stringify(detail).includes('PRIVATE-ACCESS'),false);
 await fails(()=>scalar("select op_consultar_productos_sesion('reposicion',$1)",[privateRepo]),/acceso/);
 await fails(()=>q('select * from op_busqueda_productos_base'),/permission denied/);
 await login(null,'anon');await fails(()=>search(),/permission denied/);await fails(()=>scalar("select op_consultar_productos_sesion('reposicion',$1)",[repo]),/permission denied/);
 await login(pending);await fails(()=>search(),/acceso/);await login(blankLocal);eq((await search()).total,0,'Empty approved local cannot match placeholder empty routes');
 await login(supervisor);eq((await search()).total,2,'Supervisor sees full authorized company history');
 await db.exec('reset role');
 for(let i=0;i<28;i++)await q("insert into op_reposiciones(nombre,origen_local,destino_local,created_by,created_at,updated_at) values($1,'Punta del Este','Maldonado',$2,'2026-01-01','2026-01-01')",['Paginada '+String(i).padStart(2,'0'),origin]);
 await login();const p1=await search('reposicion',{query:'Paginada',sort:'name'}),p2=await search('reposicion',{query:'Paginada',sort:'name'},1);
 eq(p1.total,28);eq(p1.sessions.length,24);eq(p2.sessions.length,4);eq(new Set([...p1.sessions,...p2.sessions].map(s=>s.id)).size,28,'Stable nonduplicating pagination');
 eq((await search('reposicion',{query:'Paginada',facets:false})).facets,null,'Optional facets avoid repeated payload');
 await db.exec('reset role');await q("insert into op_reposicion_items(reposicion_id,codigo,nombre,pedido_reposicion,stock_origen) select $1,'LARGE-'||n,'Producto masivo '||n,1,2 from generate_series(1,1205) n",[repo]);
 await login();eq((await search('reposicion',{product:'LARGE-1205'})).total,1,'Search is not truncated at the API 1000-row limit');
 const large=await search('reposicion',{query:'histórica'});eq(large.sessions[0].summary.products,1207,'Summary includes all items, not only a first page');
 console.log('session-directory SQL: '+checks+' assertions passed (all modules, permission isolation, products, stocks, history, dates, pagination).');await db.close();
}
main().catch(e=>{console.error(e.message,e.where||'');process.exit(1);});
