-- Pedidos publicos por enlace revocable y seguimiento individual.
-- Los visitantes no reciben permisos directos sobre tablas: todas las
-- operaciones anonimas pasan por RPC SECURITY DEFINER con tokens hasheados.

create extension if not exists pgcrypto with schema extensions;

alter table public.pedidos
  add column if not exists canal_creacion text not null default 'interno';

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname='pedidos_canal_creacion_check'
      and conrelid='public.pedidos'::regclass
  ) then
    alter table public.pedidos add constraint pedidos_canal_creacion_check
      check (canal_creacion in ('interno','publico'));
  end if;
end $$;

create table if not exists public.pedido_enlaces_publicos (
  id uuid primary key default gen_random_uuid(),
  local_id uuid not null references public.locales(id) on delete cascade,
  token_hash text not null unique,
  activo boolean not null default true,
  created_by uuid not null references public.perfiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  revoked_at timestamptz
);

create unique index if not exists pedido_enlaces_publicos_local_activo_idx
  on public.pedido_enlaces_publicos(local_id) where activo;
create index if not exists pedido_enlaces_publicos_local_fecha_idx
  on public.pedido_enlaces_publicos(local_id,created_at desc);

create table if not exists public.pedido_seguimientos_publicos (
  pedido_id uuid primary key references public.pedidos(id) on delete cascade,
  token_hash text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  revoked_at timestamptz
);

create table if not exists public.pedido_publico_limites (
  id bigint generated by default as identity primary key,
  enlace_id uuid not null references public.pedido_enlaces_publicos(id) on delete cascade,
  dispositivo_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists pedido_publico_limites_enlace_idx
  on public.pedido_publico_limites(enlace_id,created_at desc);
create index if not exists pedido_publico_limites_dispositivo_idx
  on public.pedido_publico_limites(enlace_id,dispositivo_hash,created_at desc);

alter table public.pedido_enlaces_publicos enable row level security;
alter table public.pedido_seguimientos_publicos enable row level security;
alter table public.pedido_publico_limites enable row level security;

revoke all on table public.pedido_enlaces_publicos from anon,authenticated;
revoke all on table public.pedido_seguimientos_publicos from anon,authenticated;
revoke all on table public.pedido_publico_limites from anon,authenticated;

create or replace function public.pedido_publico_normalizar(p_valor text)
returns text
language sql immutable
set search_path=public
as $$
  select trim(regexp_replace(
    translate(lower(coalesce(p_valor,'')),
      'áàäâéèëêíìïîóòöôúùüûñç',
      'aaaaeeeeiiiioooouuuunc'),
    '[^a-z0-9]+',' ','g'))
$$;

create or replace function public.pedido_publico_enlace_estado(p_local uuid)
returns jsonb
language plpgsql security definer
set search_path=public,extensions
as $$
declare enlace public.pedido_enlaces_publicos; local_row public.locales;
begin
  if not public.is_ops_supervisor() then raise exception 'Acceso no autorizado'; end if;
  select * into local_row from public.locales where id=p_local;
  if local_row.id is null then raise exception 'El local no existe'; end if;
  select * into enlace from public.pedido_enlaces_publicos
    where local_id=p_local order by created_at desc limit 1;
  return jsonb_build_object(
    'ok',true,
    'local',jsonb_build_object('id',local_row.id,'nombre',local_row.nombre,'almacen',local_row.almacen),
    'link_id',enlace.id,
    'active',coalesce(enlace.activo,false) and enlace.revoked_at is null,
    'revoked',enlace.revoked_at is not null,
    'created_at',enlace.created_at,
    'updated_at',enlace.updated_at
  );
end $$;

create or replace function public.pedido_publico_crear_enlace(p_local uuid)
returns jsonb
language plpgsql security definer
set search_path=public,extensions
as $$
declare token text; enlace public.pedido_enlaces_publicos; local_row public.locales;
begin
  if not public.is_ops_supervisor() then raise exception 'Solamente un supervisor puede administrar enlaces publicos'; end if;
  select * into local_row from public.locales where id=p_local;
  if local_row.id is null then raise exception 'El local no existe'; end if;
  perform pg_advisory_xact_lock(hashtextextended('pedido-publico:'||p_local::text,0));
  update public.pedido_enlaces_publicos
    set activo=false,revoked_at=coalesce(revoked_at,now()),updated_at=now()
    where local_id=p_local and revoked_at is null;
  token:=encode(gen_random_bytes(24),'hex');
  insert into public.pedido_enlaces_publicos(local_id,token_hash,activo,created_by)
  values(p_local,encode(digest(token,'sha256'),'hex'),true,auth.uid())
  returning * into enlace;
  return jsonb_build_object(
    'ok',true,'token',token,'link_id',enlace.id,'active',true,
    'local',jsonb_build_object('id',local_row.id,'nombre',local_row.nombre,'almacen',local_row.almacen),
    'created_at',enlace.created_at
  );
end $$;

create or replace function public.pedido_publico_configurar_enlace(p_local uuid,p_accion text)
returns jsonb
language plpgsql security definer
set search_path=public,extensions
as $$
declare enlace public.pedido_enlaces_publicos;
begin
  if not public.is_ops_supervisor() then raise exception 'Solamente un supervisor puede administrar enlaces publicos'; end if;
  if p_accion not in ('pausar','reactivar') then raise exception 'Accion no valida'; end if;
  perform pg_advisory_xact_lock(hashtextextended('pedido-publico:'||p_local::text,0));
  select * into enlace from public.pedido_enlaces_publicos
    where local_id=p_local and revoked_at is null order by created_at desc limit 1 for update;
  if enlace.id is null then raise exception 'No existe un enlace que pueda reactivarse'; end if;
  update public.pedido_enlaces_publicos
    set activo=(p_accion='reactivar'),updated_at=now()
    where id=enlace.id;
  return public.pedido_publico_enlace_estado(p_local);
end $$;

create or replace function public.pedido_publico_previsualizar_enlace(p_token text)
returns jsonb
language plpgsql security definer
set search_path=public,extensions
as $$
declare enlace public.pedido_enlaces_publicos; local_row public.locales;
begin
  select * into enlace from public.pedido_enlaces_publicos
    where token_hash=encode(digest(coalesce(p_token,''),'sha256'),'hex')
    order by created_at desc limit 1;
  if enlace.id is null then return jsonb_build_object('ok',false,'code','invalid','error','Enlace de pedidos invalido'); end if;
  select * into local_row from public.locales where id=enlace.local_id;
  if enlace.revoked_at is not null then return jsonb_build_object('ok',false,'code','replaced','error','Este enlace fue reemplazado'); end if;
  if not enlace.activo then return jsonb_build_object('ok',false,'code','paused','error','Este enlace esta pausado'); end if;
  if local_row.id is null then return jsonb_build_object('ok',false,'code','invalid','error','El local ya no esta disponible'); end if;
  return jsonb_build_object('ok',true,'local',jsonb_build_object('id',local_row.id,'nombre',local_row.nombre,'almacen',local_row.almacen));
end $$;

create or replace function public.pedido_publico_buscar_productos(p_token text,p_consulta text)
returns jsonb
language plpgsql security definer
set search_path=public,extensions
as $$
declare enlace_id uuid; consulta text; resultados jsonb;
begin
  select id into enlace_id from public.pedido_enlaces_publicos
    where token_hash=encode(digest(coalesce(p_token,''),'sha256'),'hex')
      and activo and revoked_at is null limit 1;
  if enlace_id is null then return jsonb_build_object('ok',false,'code','invalid','error','El enlace ya no esta disponible'); end if;
  consulta:=public.pedido_publico_normalizar(p_consulta);
  if char_length(consulta)<2 then return jsonb_build_object('ok',false,'code','short_query','error','Escribi al menos dos caracteres'); end if;
  with catalogo as (
    select codigo,nombre,coalesce(marca,'') marca,1 prioridad from public.productos
      where nullif(trim(codigo),'') is not null
    union all
    select codigo,nombre,coalesce(marca,'') marca,2 prioridad from public.padron_extra
      where nullif(trim(codigo),'') is not null
  ), unicos as (
    select distinct on (codigo) codigo,nombre,marca
    from catalogo c
    where not exists (
      select 1 from regexp_split_to_table(consulta,'\s+') termino
      where public.pedido_publico_normalizar(concat_ws(' ',c.codigo,c.nombre,c.marca)) not like '%'||termino||'%'
    )
    order by codigo,prioridad
  )
  select coalesce(jsonb_agg(jsonb_build_object('codigo',codigo,'nombre',nombre,'marca',marca) order by nombre),'[]'::jsonb)
    into resultados from (select * from unicos order by nombre limit 30) x;
  return jsonb_build_object('ok',true,'products',resultados);
end $$;

create or replace function public.pedido_publico_crear(
  p_enlace text,
  p_nombre text,
  p_apellido text,
  p_telefono text,
  p_origen uuid,
  p_productos jsonb,
  p_urgente boolean,
  p_notas text,
  p_dispositivo text,
  p_confirmar_duplicado boolean default false
)
returns jsonb
language plpgsql security definer
set search_path=public,extensions
as $$
declare
  enlace public.pedido_enlaces_publicos;
  origen public.locales;
  destino public.locales;
  pedido_id uuid;
  token_seguimiento text;
  v_dispositivo_hash text;
  nombre_completo text;
  telefono_limpio text;
  faltante text;
  duplicados integer;
  productos_duplicados jsonb;
  codigo_pedido text;
  escala_nombre text;
  escala_almacen text;
begin
  select * into enlace from public.pedido_enlaces_publicos
    where token_hash=encode(digest(coalesce(p_enlace,''),'sha256'),'hex')
      and activo and revoked_at is null limit 1 for update;
  if enlace.id is null then raise exception 'El enlace de pedidos ya no esta disponible'; end if;
  select * into destino from public.locales where id=enlace.local_id;
  select * into origen from public.locales where id=p_origen;
  if destino.id is null or origen.id is null then raise exception 'El origen o destino ya no esta disponible'; end if;
  if origen.id=destino.id then raise exception 'Origen y destino no pueden ser iguales'; end if;
  if char_length(trim(coalesce(p_nombre,''))) not between 2 and 80 then raise exception 'El nombre debe tener entre 2 y 80 caracteres'; end if;
  if char_length(trim(coalesce(p_apellido,''))) not between 2 and 80 then raise exception 'El apellido debe tener entre 2 y 80 caracteres'; end if;
  if char_length(trim(coalesce(p_telefono,'')))>30 then raise exception 'El telefono es demasiado largo'; end if;
  if char_length(trim(coalesce(p_notas,'')))>500 then raise exception 'Las notas admiten hasta 500 caracteres'; end if;
  if char_length(trim(coalesce(p_dispositivo,''))) not between 8 and 120 then raise exception 'No se pudo identificar este dispositivo'; end if;
  if p_productos is null or jsonb_typeof(p_productos)<>'array' or jsonb_array_length(p_productos) not between 1 and 100 then
    raise exception 'El pedido debe contener entre 1 y 100 productos';
  end if;
  if exists (
    select 1 from jsonb_array_elements(p_productos) item
    where jsonb_typeof(item)<>'object'
      or nullif(trim(item->>'codigo'),'') is null
      or case when coalesce(item->>'cantidad','') ~ '^\d{1,4}$'
        then (item->>'cantidad')::integer not between 1 and 999 else true end
  ) then raise exception 'Hay productos o cantidades invalidas'; end if;
  if exists (
    with solicitados as (
      select trim(item->>'codigo') codigo,sum((item->>'cantidad')::integer) cantidad
      from jsonb_array_elements(p_productos) item group by trim(item->>'codigo')
    ) select 1 from solicitados where cantidad>999
  ) then raise exception 'La cantidad maxima por producto es 999'; end if;

  with solicitados as (
    select distinct trim(item->>'codigo') codigo from jsonb_array_elements(p_productos) item
  ), catalogo as (
    select codigo from public.productos where nullif(trim(codigo),'') is not null
    union select codigo from public.padron_extra where nullif(trim(codigo),'') is not null
  )
  select string_agg(s.codigo,', ') into faltante from solicitados s
    where not exists(select 1 from catalogo c where c.codigo=s.codigo);
  if faltante is not null then raise exception 'Productos inexistentes: %',left(faltante,240); end if;

  nombre_completo:=regexp_replace(trim(p_nombre)||' '||trim(p_apellido),'\s+',' ','g');
  telefono_limpio:=regexp_replace(coalesce(p_telefono,''),'\D','','g');
  with solicitados as (
    select distinct trim(item->>'codigo') codigo from jsonb_array_elements(p_productos) item
  ), candidatos as (
    select distinct p.id
    from public.pedidos p join public.pedido_productos pp on pp.pedido_id=p.id
    where p.origen_local=origen.nombre and p.destino_local=destino.nombre
      and (p.created_at at time zone 'America/Montevideo')::date=(now() at time zone 'America/Montevideo')::date
      and p.estado<>'denegado'
      and (
        (telefono_limpio<>'' and regexp_replace(coalesce(p.telefono,''),'\D','','g')=telefono_limpio)
        or (telefono_limpio='' and public.pedido_publico_normalizar(p.cliente)=public.pedido_publico_normalizar(nombre_completo))
      )
      and pp.codigo in (select codigo from solicitados)
  ) select count(*) into duplicados from candidatos;
  if duplicados>0 and not coalesce(p_confirmar_duplicado,false) then
    with solicitados as (
      select distinct trim(item->>'codigo') codigo from jsonb_array_elements(p_productos) item
    ), nombres as (
      select distinct pp.nombre from public.pedidos p join public.pedido_productos pp on pp.pedido_id=p.id
      where p.origen_local=origen.nombre and p.destino_local=destino.nombre
        and (p.created_at at time zone 'America/Montevideo')::date=(now() at time zone 'America/Montevideo')::date
        and p.estado<>'denegado' and pp.codigo in (select codigo from solicitados) limit 5
    ) select coalesce(jsonb_agg(nombre),'[]'::jsonb) into productos_duplicados from nombres;
    return jsonb_build_object('ok',false,'code','possible_duplicate','count',duplicados,'products',productos_duplicados);
  end if;

  perform pg_advisory_xact_lock(hashtextextended('pedido-publico-rate:'||enlace.id::text,0));
  delete from public.pedido_publico_limites where created_at<now()-interval '2 days';
  v_dispositivo_hash:=encode(digest(enlace.id::text||':'||trim(p_dispositivo),'sha256'),'hex');
  if (select count(*) from public.pedido_publico_limites where enlace_id=enlace.id and created_at>=now()-interval '1 hour')>=100 then
    raise exception 'Este enlace alcanzo temporalmente el limite de pedidos';
  end if;
  if (select count(*) from public.pedido_publico_limites limite where limite.enlace_id=enlace.id and limite.dispositivo_hash=v_dispositivo_hash and limite.created_at>=now()-interval '15 minutes')>=5 then
    raise exception 'Este dispositivo alcanzo temporalmente el limite de pedidos';
  end if;

  if destino.nombre='Maldonado' then
    escala_nombre:='Punta del Este'; escala_almacen:='PDE';
  end if;
  insert into public.pedidos(
    origen_local,origen_almacen,destino_local,destino_almacen,cliente,telefono,
    urgente,duplicado_confirmado,notas,escala_local,escala_almacen,estado,creado_por,canal_creacion
  ) values (
    origen.nombre,origen.almacen,destino.nombre,destino.almacen,nombre_completo,nullif(trim(p_telefono),''),
    coalesce(p_urgente,false),coalesce(p_confirmar_duplicado,false),nullif(trim(p_notas),''),
    escala_nombre,escala_almacen,'pendiente',null,'publico'
  ) returning id into pedido_id;

  with solicitados as (
    select trim(item->>'codigo') codigo,sum((item->>'cantidad')::integer)::integer cantidad
    from jsonb_array_elements(p_productos) item group by trim(item->>'codigo')
  ), catalogo as (
    select codigo,nombre,coalesce(marca,'') marca,1 prioridad from public.productos
    union all
    select codigo,nombre,coalesce(marca,'') marca,2 prioridad from public.padron_extra
  ), unicos as (
    select distinct on (codigo) codigo,nombre,marca from catalogo order by codigo,prioridad
  )
  insert into public.pedido_productos(pedido_id,codigo,nombre,marca,cantidad)
    select pedido_id,u.codigo,u.nombre,u.marca,s.cantidad from solicitados s join unicos u on u.codigo=s.codigo;

  insert into public.pedido_historial(pedido_id,estado,usuario_id,persona_nombre)
    values(pedido_id,'pendiente',null,nombre_completo);
  token_seguimiento:=encode(gen_random_bytes(24),'hex');
  insert into public.pedido_seguimientos_publicos(pedido_id,token_hash)
    values(pedido_id,encode(digest(token_seguimiento,'sha256'),'hex'));
  codigo_pedido:=upper(substring(pedido_id::text from char_length(pedido_id::text)-7 for 6));
  insert into public.notificaciones(usuario_id,titulo,cuerpo,pedido_id)
    select p.id,'📦 Nuevo pedido publico de '||destino.nombre,
      '#'||codigo_pedido||' · '||nombre_completo,pedido_id
    from public.perfiles p where p.approved=true and p.local_nombre=origen.nombre;
  insert into public.pedido_publico_limites(enlace_id,dispositivo_hash) values(enlace.id,v_dispositivo_hash);
  return jsonb_build_object(
    'ok',true,'order_id',pedido_id,'order_code',codigo_pedido,
    'tracking_token',token_seguimiento,
    'customer',nombre_completo,'origin',origen.nombre,'destination',destino.nombre,
    'created_at',now()
  );
end $$;

create or replace function public.pedido_publico_seguimiento(p_token text)
returns jsonb
language plpgsql security definer
set search_path=public,extensions
as $$
declare pedido public.pedidos; productos jsonb; historial jsonb; codigo_pedido text;
begin
  select p.* into pedido
  from public.pedido_seguimientos_publicos s join public.pedidos p on p.id=s.pedido_id
  where s.token_hash=encode(digest(coalesce(p_token,''),'sha256'),'hex') and s.revoked_at is null limit 1;
  if pedido.id is null then return jsonb_build_object('ok',false,'code','invalid','error','Enlace de seguimiento invalido'); end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'codigo',pp.codigo,'nombre',pp.nombre,'marca',coalesce(pp.marca,''),'cantidad',pp.cantidad,
    'cantidad_aceptada',pp.cantidad_aceptada,'cantidad_preparada',pp.cantidad_preparada
  ) order by pp.nombre),'[]'::jsonb) into productos
  from public.pedido_productos pp where pp.pedido_id=pedido.id;
  select coalesce(jsonb_agg(jsonb_build_object('estado',h.estado,'created_at',h.created_at) order by h.created_at),'[]'::jsonb)
    into historial from public.pedido_historial h where h.pedido_id=pedido.id;
  codigo_pedido:=upper(substring(pedido.id::text from char_length(pedido.id::text)-7 for 6));
  return jsonb_build_object(
    'ok',true,'order',jsonb_build_object(
      'code',codigo_pedido,'customer',pedido.cliente,'state',pedido.estado,'urgent',coalesce(pedido.urgente,false),
      'origin',jsonb_build_object('name',pedido.origen_local,'warehouse',pedido.origen_almacen),
      'destination',jsonb_build_object('name',pedido.destino_local,'warehouse',pedido.destino_almacen),
      'scale',case when pedido.escala_local is null then null else jsonb_build_object('name',pedido.escala_local,'warehouse',pedido.escala_almacen) end,
      'created_at',pedido.created_at,'updated_at',pedido.updated_at,'products',productos,'timeline',historial
    )
  );
end $$;

create or replace function public.pedido_publico_regenerar_seguimiento(p_pedido uuid)
returns jsonb
language plpgsql security definer
set search_path=public,extensions
as $$
declare token text; codigo_pedido text;
begin
  if auth.uid() is null or not public.can_access_order(p_pedido) then raise exception 'Acceso no autorizado'; end if;
  token:=encode(gen_random_bytes(24),'hex');
  insert into public.pedido_seguimientos_publicos(pedido_id,token_hash,created_at,updated_at,revoked_at)
    values(p_pedido,encode(digest(token,'sha256'),'hex'),now(),now(),null)
  on conflict(pedido_id) do update set token_hash=excluded.token_hash,updated_at=now(),revoked_at=null;
  codigo_pedido:=upper(substring(p_pedido::text from char_length(p_pedido::text)-7 for 6));
  return jsonb_build_object('ok',true,'order_code',codigo_pedido,'tracking_token',token);
end $$;

create or replace function public.pedido_publico_resolver_gestion(p_token text)
returns jsonb
language plpgsql security definer
set search_path=public,extensions
as $$
declare v_pedido_id uuid;
begin
  if auth.uid() is null then raise exception 'Debes iniciar sesion'; end if;
  select s.pedido_id into v_pedido_id from public.pedido_seguimientos_publicos s
    where token_hash=encode(digest(coalesce(p_token,''),'sha256'),'hex') and revoked_at is null limit 1;
  if v_pedido_id is null or not public.can_access_order(v_pedido_id) then raise exception 'No tienes permisos para gestionar este pedido'; end if;
  return jsonb_build_object('ok',true,'order_id',v_pedido_id);
end $$;

revoke all on function public.pedido_publico_normalizar(text) from public;
revoke all on function public.pedido_publico_enlace_estado(uuid) from public;
revoke all on function public.pedido_publico_crear_enlace(uuid) from public;
revoke all on function public.pedido_publico_configurar_enlace(uuid,text) from public;
revoke all on function public.pedido_publico_previsualizar_enlace(text) from public;
revoke all on function public.pedido_publico_buscar_productos(text,text) from public;
revoke all on function public.pedido_publico_crear(text,text,text,text,uuid,jsonb,boolean,text,text,boolean) from public;
revoke all on function public.pedido_publico_seguimiento(text) from public;
revoke all on function public.pedido_publico_regenerar_seguimiento(uuid) from public;
revoke all on function public.pedido_publico_resolver_gestion(text) from public;

grant execute on function public.pedido_publico_enlace_estado(uuid) to authenticated;
grant execute on function public.pedido_publico_crear_enlace(uuid) to authenticated;
grant execute on function public.pedido_publico_configurar_enlace(uuid,text) to authenticated;
grant execute on function public.pedido_publico_previsualizar_enlace(text) to anon,authenticated;
grant execute on function public.pedido_publico_buscar_productos(text,text) to anon,authenticated;
grant execute on function public.pedido_publico_crear(text,text,text,text,uuid,jsonb,boolean,text,text,boolean) to anon,authenticated;
grant execute on function public.pedido_publico_seguimiento(text) to anon,authenticated;
grant execute on function public.pedido_publico_regenerar_seguimiento(uuid) to authenticated;
grant execute on function public.pedido_publico_resolver_gestion(text) to authenticated;
