-- Recepción colaborativa de remitos y cierre integrado con pedidos entre locales.

create table if not exists public.op_local_aliases (
  alias text primary key,
  local_nombre text not null,
  created_at timestamptz not null default now()
);

insert into public.op_local_aliases(alias,local_nombre)
select 'Bloqueo Punta del Este','Punta del Este'
where exists(select 1 from public.locales where nombre='Punta del Este')
on conflict(alias) do update set local_nombre=excluded.local_nombre;

create table if not exists public.op_recepciones (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  numero_remito text not null,
  fecha_remito date not null,
  origen_local text not null,
  destino_local text not null,
  estado text not null default 'en_control' check (estado in ('en_control','cerrado','archivado')),
  original_filename text,
  original_path text,
  import_meta jsonb not null default '{}'::jsonb,
  observaciones_cierre text,
  created_by uuid not null references public.perfiles(id),
  closed_by uuid references public.perfiles(id),
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(numero_remito,fecha_remito,origen_local,destino_local)
);

create table if not exists public.op_recepcion_items (
  recepcion_id uuid not null references public.op_recepciones(id) on delete cascade,
  codigo text not null,
  nombre text not null,
  descripcion_archivo text,
  barras text,
  marca text,
  esperado integer not null check (esperado > 0),
  recibido integer not null default 0 check (recibido >= 0),
  no_recibido boolean not null default false,
  observacion text,
  source_lines jsonb not null default '[]'::jsonb,
  updated_by uuid references public.perfiles(id),
  updated_by_name text,
  updated_at timestamptz not null default now(),
  primary key(recepcion_id,codigo)
);

create table if not exists public.op_recepcion_extras (
  recepcion_id uuid not null references public.op_recepciones(id) on delete cascade,
  codigo text not null,
  nombre text not null,
  barras text,
  cantidad integer not null default 0 check (cantidad >= 0),
  observacion text,
  updated_by uuid references public.perfiles(id),
  updated_by_name text,
  updated_at timestamptz not null default now(),
  primary key(recepcion_id,codigo)
);

create table if not exists public.op_recepcion_participantes (
  recepcion_id uuid not null references public.op_recepciones(id) on delete cascade,
  usuario_id uuid not null references public.perfiles(id),
  nombre text not null,
  joined_at timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  primary key(recepcion_id,usuario_id)
);

create table if not exists public.op_recepcion_eventos (
  id bigint generated by default as identity primary key,
  recepcion_id uuid not null references public.op_recepciones(id) on delete cascade,
  usuario_id uuid references public.perfiles(id),
  usuario_nombre text,
  accion text not null,
  codigo text,
  detalle jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.op_recepcion_pedidos (
  recepcion_id uuid not null references public.op_recepciones(id) on delete cascade,
  pedido_id uuid not null references public.pedidos(id),
  coincidencia text not null default 'ruta_sku' check (coincidencia in ('remito','despacho','ruta_sku')),
  linked_at timestamptz not null default now(),
  primary key(recepcion_id,pedido_id)
);

alter table public.pedido_productos add column if not exists cantidad_recibida integer not null default 0;
alter table public.pedidos add column if not exists recepcion_id uuid references public.op_recepciones(id) on delete set null;
alter table public.pedidos add column if not exists cliente_aviso_pendiente boolean not null default false;
alter table public.pedidos add column if not exists cliente_avisado_at timestamptz;
alter table public.pedidos add column if not exists cliente_avisado_by uuid references public.perfiles(id) on delete set null;

create index if not exists op_recepciones_destino_estado_idx on public.op_recepciones(destino_local,estado,updated_at desc);
create index if not exists op_recepcion_items_codigo_idx on public.op_recepcion_items(codigo);
create index if not exists op_recepcion_pedidos_pedido_idx on public.op_recepcion_pedidos(pedido_id);

create or replace function public.op_crear_recepcion(
  p_nombre text,p_numero_remito text,p_fecha_remito date,p_origen text,p_destino text,
  p_items jsonb,p_import_meta jsonb default '{}'::jsonb,p_original_filename text default null
) returns uuid language plpgsql security definer set search_path=public,pg_temp as $$
declare r uuid; nombre_usuario text;
begin
  if trim(coalesce(p_numero_remito,''))='' or p_fecha_remito is null or trim(coalesce(p_origen,''))='' or trim(coalesce(p_destino,''))='' then
    raise exception 'Faltan número, fecha, origen o destino del remito';
  end if;
  if jsonb_typeof(p_items)<>'array' or jsonb_array_length(p_items)=0 then raise exception 'El remito no contiene productos'; end if;
  if not (public.is_ops_supervisor() or trim(p_destino)=public.my_local()) then raise exception 'Solamente el local destino puede crear esta recepción'; end if;
  if exists(select 1 from public.op_recepciones where numero_remito=trim(p_numero_remito) and fecha_remito=p_fecha_remito and origen_local=trim(p_origen) and destino_local=trim(p_destino)) then
    raise exception 'Este remito ya fue cargado. Abrí la recepción existente';
  end if;
  select left(coalesce(nullif(trim(coalesce(nombre,'')||' '||coalesce(apellido,'')),''),'Usuario'),80) into nombre_usuario from public.perfiles where id=auth.uid();
  nombre_usuario:=coalesce(nombre_usuario,'Usuario');

  insert into public.op_recepciones(nombre,numero_remito,fecha_remito,origen_local,destino_local,original_filename,import_meta,created_by)
  values(coalesce(nullif(trim(p_nombre),''),'Remito '||trim(p_numero_remito)),trim(p_numero_remito),p_fecha_remito,trim(p_origen),trim(p_destino),nullif(trim(p_original_filename),''),coalesce(p_import_meta,'{}'::jsonb),auth.uid())
  returning id into r;

  insert into public.op_recepcion_items(recepcion_id,codigo,nombre,descripcion_archivo,barras,marca,esperado,source_lines,updated_by,updated_by_name)
  select r,trim(x->>'codigo'),coalesce(nullif(trim(x->>'nombre'),''),trim(x->>'codigo')),nullif(trim(x->>'descripcion_archivo'),''),
    nullif(trim(x->>'barras'),''),nullif(trim(x->>'marca'),''),greatest(1,(x->>'esperado')::integer),coalesce(x->'source_lines','[]'::jsonb),auth.uid(),nombre_usuario
  from jsonb_array_elements(p_items) x where trim(coalesce(x->>'codigo',''))<>'' and coalesce((x->>'esperado')::integer,0)>0;

  -- Prioridad: mismo número de remito. Si el pedido aún no tenía número,
  -- se vincula por recorrido y SKU mientras continúe En viaje.
  insert into public.op_recepcion_pedidos(recepcion_id,pedido_id,coincidencia)
  select r,p.id,case when nullif(trim(p.remito),'')=trim(p_numero_remito) then 'remito' when p.despacho_id is not null then 'despacho' else 'ruta_sku' end
  from public.pedidos p
  where p.estado in ('transito','llegado') and p.origen_local=trim(p_origen) and p.destino_local=trim(p_destino)
    and (nullif(trim(p.remito),'') is null or trim(p.remito)=trim(p_numero_remito))
    and exists(
      select 1 from public.pedido_productos pp join public.op_recepcion_items ri on ri.recepcion_id=r and ri.codigo=pp.codigo
      where pp.pedido_id=p.id and coalesce(pp.cantidad_preparada,0)>0
    )
  on conflict do nothing;

  update public.pedidos p set recepcion_id=r,updated_at=now()
  where exists(select 1 from public.op_recepcion_pedidos rp where rp.recepcion_id=r and rp.pedido_id=p.id);
  insert into public.op_recepcion_participantes(recepcion_id,usuario_id,nombre) values(r,auth.uid(),nombre_usuario);
  insert into public.op_recepcion_eventos(recepcion_id,usuario_id,usuario_nombre,accion,detalle)
  values(r,auth.uid(),nombre_usuario,'crear',jsonb_build_object('numero_remito',trim(p_numero_remito),'productos',jsonb_array_length(p_items)));
  return r;
end $$;

create or replace function public.op_recepcion_cantidad(
  p_recepcion uuid,p_codigo text,p_delta integer default null,p_absoluta integer default null,
  p_origen text default 'manual',p_usuario_nombre text default 'Usuario'
) returns jsonb language plpgsql security definer set search_path=public as $$
declare item public.op_recepcion_items; nueva integer;
begin
  if not exists(select 1 from public.op_recepciones r where r.id=p_recepcion and r.estado='en_control' and (public.is_ops_supervisor() or r.destino_local=public.my_local())) then raise exception 'Recepción no disponible'; end if;
  select * into item from public.op_recepcion_items where recepcion_id=p_recepcion and codigo=trim(p_codigo) for update;
  if item.codigo is null then raise exception 'Producto no incluido en el remito'; end if;
  nueva:=case when p_absoluta is not null then p_absoluta else item.recibido+coalesce(p_delta,0) end;
  if nueva<0 or nueva>999999 then raise exception 'Cantidad inválida'; end if;
  update public.op_recepcion_items set recibido=nueva,no_recibido=case when nueva>0 then false else no_recibido end,
    updated_by=auth.uid(),updated_by_name=left(coalesce(nullif(trim(p_usuario_nombre),''),'Usuario'),80),updated_at=now()
  where recepcion_id=p_recepcion and codigo=trim(p_codigo) returning * into item;
  insert into public.op_recepcion_eventos(recepcion_id,usuario_id,usuario_nombre,accion,codigo,detalle)
  values(p_recepcion,auth.uid(),left(coalesce(nullif(trim(p_usuario_nombre),''),'Usuario'),80),'cantidad',item.codigo,jsonb_build_object('despues',nueva,'origen',p_origen));
  update public.op_recepciones set updated_at=now() where id=p_recepcion;
  return to_jsonb(item);
end $$;

create or replace function public.op_recepcion_no_recibido(p_recepcion uuid,p_codigo text,p_valor boolean,p_observacion text default null,p_usuario_nombre text default 'Usuario')
returns jsonb language plpgsql security definer set search_path=public as $$
declare item public.op_recepcion_items;
begin
  if not exists(select 1 from public.op_recepciones r where r.id=p_recepcion and r.estado='en_control' and (public.is_ops_supervisor() or r.destino_local=public.my_local())) then raise exception 'Recepción no disponible'; end if;
  update public.op_recepcion_items set no_recibido=coalesce(p_valor,false),recibido=case when coalesce(p_valor,false) then 0 else recibido end,
    observacion=nullif(trim(coalesce(p_observacion,'')),''),updated_by=auth.uid(),updated_by_name=left(coalesce(nullif(trim(p_usuario_nombre),''),'Usuario'),80),updated_at=now()
  where recepcion_id=p_recepcion and codigo=trim(p_codigo) returning * into item;
  if item.codigo is null then raise exception 'Producto no encontrado'; end if;
  insert into public.op_recepcion_eventos(recepcion_id,usuario_id,usuario_nombre,accion,codigo,detalle)
  values(p_recepcion,auth.uid(),left(coalesce(nullif(trim(p_usuario_nombre),''),'Usuario'),80),'no_recibido',item.codigo,jsonb_build_object('valor',p_valor,'observacion',p_observacion));
  update public.op_recepciones set updated_at=now() where id=p_recepcion;
  return to_jsonb(item);
end $$;

create or replace function public.op_recepcion_extra(
  p_recepcion uuid,p_codigo text,p_nombre text,p_barras text default null,p_delta integer default null,
  p_absoluta integer default null,p_observacion text default null,p_usuario_nombre text default 'Usuario'
) returns jsonb language plpgsql security definer set search_path=public as $$
declare item public.op_recepcion_extras; actual integer:=0; nueva integer;
begin
  if not exists(select 1 from public.op_recepciones r where r.id=p_recepcion and r.estado='en_control' and (public.is_ops_supervisor() or r.destino_local=public.my_local())) then raise exception 'Recepción no disponible'; end if;
  select * into item from public.op_recepcion_extras where recepcion_id=p_recepcion and codigo=trim(p_codigo) for update;
  actual:=coalesce(item.cantidad,0);
  nueva:=case when p_absoluta is not null then p_absoluta else actual+coalesce(p_delta,0) end;
  if nueva<0 or nueva>999999 then raise exception 'Cantidad inválida'; end if;
  insert into public.op_recepcion_extras(recepcion_id,codigo,nombre,barras,cantidad,observacion,updated_by,updated_by_name)
  values(p_recepcion,trim(p_codigo),coalesce(nullif(trim(p_nombre),''),trim(p_codigo)),nullif(trim(coalesce(p_barras,'')),''),nueva,nullif(trim(coalesce(p_observacion,'')),''),auth.uid(),left(coalesce(nullif(trim(p_usuario_nombre),''),'Usuario'),80))
  on conflict(recepcion_id,codigo) do update set cantidad=excluded.cantidad,nombre=excluded.nombre,barras=coalesce(excluded.barras,public.op_recepcion_extras.barras),
    observacion=coalesce(excluded.observacion,public.op_recepcion_extras.observacion),updated_by=auth.uid(),updated_by_name=excluded.updated_by_name,updated_at=now()
  returning * into item;
  insert into public.op_recepcion_eventos(recepcion_id,usuario_id,usuario_nombre,accion,codigo,detalle)
  values(p_recepcion,auth.uid(),left(coalesce(nullif(trim(p_usuario_nombre),''),'Usuario'),80),'extra',item.codigo,jsonb_build_object('despues',nueva));
  update public.op_recepciones set updated_at=now() where id=p_recepcion;
  return to_jsonb(item);
end $$;

create or replace function public.op_recepcion_cerrar(p_recepcion uuid,p_observaciones text default null)
returns jsonb language plpgsql security definer set search_path=public as $$
declare rec public.op_recepciones; nombre_usuario text; vinculados integer:=0; completos integer:=0; incompletos integer:=0; pendientes integer:=0;
begin
  select * into rec from public.op_recepciones where id=p_recepcion for update;
  if rec.id is null or rec.estado<>'en_control' or not (public.is_ops_supervisor() or rec.destino_local=public.my_local()) then raise exception 'Recepción no disponible'; end if;
  select left(coalesce(nullif(trim(coalesce(nombre,'')||' '||coalesce(apellido,'')),''),'Usuario'),80) into nombre_usuario from public.perfiles where id=auth.uid();
  nombre_usuario:=coalesce(nombre_usuario,'Usuario');
  select count(*) into pendientes from public.op_recepcion_items where recepcion_id=rec.id and recibido<esperado and not no_recibido;
  update public.op_recepcion_items set no_recibido=true,updated_by=auth.uid(),updated_by_name=nombre_usuario,updated_at=now()
  where recepcion_id=rec.id and recibido=0 and not no_recibido;

  -- Las unidades recibidas se asignan primero a pedidos de clientes, en orden de creación.
  with lineas as (
    select pp.id,pp.pedido_id,pp.codigo,greatest(0,coalesce(nullif(pp.cantidad_preparada,0),pp.cantidad_aceptada,pp.cantidad,0))::integer solicitada,
      coalesce(ri.recibido,0)::integer disponible,
      coalesce(sum(greatest(0,coalesce(nullif(pp.cantidad_preparada,0),pp.cantidad_aceptada,pp.cantidad,0))) over(partition by pp.codigo order by p.created_at,p.id,pp.id rows between unbounded preceding and 1 preceding),0)::integer previa
    from public.op_recepcion_pedidos rp join public.pedidos p on p.id=rp.pedido_id join public.pedido_productos pp on pp.pedido_id=p.id
    left join public.op_recepcion_items ri on ri.recepcion_id=rec.id and ri.codigo=pp.codigo
    where rp.recepcion_id=rec.id
  ), asignadas as (
    select id,greatest(0,least(solicitada,disponible-previa))::integer cantidad from lineas
  )
  update public.pedido_productos pp set cantidad_recibida=a.cantidad from asignadas a where pp.id=a.id;

  with totales as (
    select p.id,sum(greatest(0,coalesce(nullif(pp.cantidad_preparada,0),pp.cantidad_aceptada,pp.cantidad,0)))::integer solicitada,
      sum(coalesce(pp.cantidad_recibida,0))::integer recibida
    from public.op_recepcion_pedidos rp join public.pedidos p on p.id=rp.pedido_id join public.pedido_productos pp on pp.pedido_id=p.id
    where rp.recepcion_id=rec.id group by p.id
  )
  update public.pedidos p set estado=case when t.solicitada>0 and t.recibida>=t.solicitada then 'completo' else 'incompleto' end,
    cliente_aviso_pendiente=case when t.solicitada>0 and t.recibida>=t.solicitada and nullif(trim(coalesce(p.cliente,'')),'') is not null then true else false end,
    cliente_avisado_at=null,cliente_avisado_by=null,recepcion_id=rec.id,
    faltantes=case when t.solicitada>0 and t.recibida>=t.solicitada then null else 'Recepción del remito '||rec.numero_remito||': recibidas '||t.recibida||' de '||t.solicitada||' unidades' end,
    updated_at=now()
  from totales t where p.id=t.id;

  insert into public.pedido_historial(pedido_id,estado,usuario_id,persona_nombre)
  select rp.pedido_id,'llegado',auth.uid(),nombre_usuario from public.op_recepcion_pedidos rp where rp.recepcion_id=rec.id;
  insert into public.pedido_historial(pedido_id,estado,usuario_id,persona_nombre)
  select p.id,p.estado,auth.uid(),nombre_usuario from public.pedidos p join public.op_recepcion_pedidos rp on rp.pedido_id=p.id where rp.recepcion_id=rec.id;

  insert into public.notificaciones(usuario_id,titulo,cuerpo,pedido_id)
  select pf.id,'📞 Pedido recibido: avisar al cliente',coalesce(p.cliente,'Cliente')||' · Remito '||rec.numero_remito,p.id
  from public.pedidos p join public.op_recepcion_pedidos rp on rp.pedido_id=p.id
  join public.perfiles pf on pf.approved=true and pf.local_nombre=rec.destino_local
  where rp.recepcion_id=rec.id and p.cliente_aviso_pendiente=true;

  update public.op_recepciones set estado='cerrado',observaciones_cierre=nullif(trim(coalesce(p_observaciones,'')),''),closed_by=auth.uid(),closed_at=now(),updated_at=now() where id=rec.id;
  select count(*) into vinculados from public.op_recepcion_pedidos where recepcion_id=rec.id;
  select count(*) filter(where p.estado='completo'),count(*) filter(where p.estado='incompleto') into completos,incompletos
  from public.pedidos p join public.op_recepcion_pedidos rp on rp.pedido_id=p.id where rp.recepcion_id=rec.id;
  insert into public.op_recepcion_eventos(recepcion_id,usuario_id,usuario_nombre,accion,detalle)
  values(rec.id,auth.uid(),nombre_usuario,'cerrar',jsonb_build_object('pendientes_al_cerrar',pendientes,'pedidos_vinculados',vinculados,'pedidos_completos',completos,'pedidos_incompletos',incompletos));
  return jsonb_build_object('id',rec.id,'pendientes_al_cerrar',pendientes,'pedidos_vinculados',vinculados,'pedidos_completos',completos,'pedidos_incompletos',incompletos);
end $$;

create or replace function public.op_eliminar_recepcion(p_recepcion uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare rec public.op_recepciones;
begin
  select * into rec from public.op_recepciones where id=p_recepcion for update;
  if rec.id is null or rec.estado<>'en_control' or not (public.is_ops_supervisor() or rec.destino_local=public.my_local()) then raise exception 'Recepción no disponible para eliminar'; end if;
  update public.pedidos set recepcion_id=null,updated_at=now() where recepcion_id=rec.id and estado in ('transito','llegado');
  delete from public.op_recepciones where id=rec.id;
  return jsonb_build_object('id',rec.id,'original_path',rec.original_path,'numero_remito',rec.numero_remito);
end $$;

create or replace function public.op_marcar_cliente_avisado(p_pedido uuid)
returns boolean language plpgsql security definer set search_path=public as $$
declare pedido public.pedidos; nombre_usuario text;
begin
  select * into pedido from public.pedidos where id=p_pedido for update;
  if pedido.id is null or not (public.is_ops_supervisor() or pedido.destino_local=public.my_local()) then raise exception 'Pedido no disponible'; end if;
  if not pedido.cliente_aviso_pendiente then return false; end if;
  select left(coalesce(nullif(trim(coalesce(nombre,'')||' '||coalesce(apellido,'')),''),'Usuario'),80) into nombre_usuario from public.perfiles where id=auth.uid();
  update public.pedidos set cliente_aviso_pendiente=false,cliente_avisado_at=now(),cliente_avisado_by=auth.uid(),updated_at=now() where id=p_pedido;
  insert into public.pedido_historial(pedido_id,estado,usuario_id,persona_nombre) values(p_pedido,'cliente_avisado',auth.uid(),coalesce(nombre_usuario,'Usuario'));
  return true;
end $$;

alter table public.op_local_aliases enable row level security;
alter table public.op_recepciones enable row level security;
alter table public.op_recepcion_items enable row level security;
alter table public.op_recepcion_extras enable row level security;
alter table public.op_recepcion_participantes enable row level security;
alter table public.op_recepcion_eventos enable row level security;
alter table public.op_recepcion_pedidos enable row level security;

drop policy if exists op_local_aliases_read on public.op_local_aliases;
create policy op_local_aliases_read on public.op_local_aliases for select to authenticated using (true);
drop policy if exists op_local_aliases_admin on public.op_local_aliases;
create policy op_local_aliases_admin on public.op_local_aliases for all to authenticated using(public.is_ops_supervisor()) with check(public.is_ops_supervisor());

drop policy if exists recepciones_read on public.op_recepciones;
create policy recepciones_read on public.op_recepciones for select to authenticated using(public.is_ops_supervisor() or origen_local=public.my_local() or destino_local=public.my_local());
drop policy if exists recepciones_create on public.op_recepciones;
create policy recepciones_create on public.op_recepciones for insert to authenticated with check(created_by=auth.uid() and (public.is_ops_supervisor() or destino_local=public.my_local()));
drop policy if exists recepciones_update on public.op_recepciones;
create policy recepciones_update on public.op_recepciones for update to authenticated using(public.is_ops_supervisor() or destino_local=public.my_local()) with check(public.is_ops_supervisor() or destino_local=public.my_local());

drop policy if exists recepcion_items_read on public.op_recepcion_items;
create policy recepcion_items_read on public.op_recepcion_items for select to authenticated using(exists(select 1 from public.op_recepciones r where r.id=recepcion_id and (public.is_ops_supervisor() or r.origen_local=public.my_local() or r.destino_local=public.my_local())));
drop policy if exists recepcion_items_mutate on public.op_recepcion_items;
create policy recepcion_items_mutate on public.op_recepcion_items for all to authenticated using(exists(select 1 from public.op_recepciones r where r.id=recepcion_id and r.estado='en_control' and (public.is_ops_supervisor() or r.destino_local=public.my_local()))) with check(exists(select 1 from public.op_recepciones r where r.id=recepcion_id and r.estado='en_control' and (public.is_ops_supervisor() or r.destino_local=public.my_local())));

drop policy if exists recepcion_extras_read on public.op_recepcion_extras;
create policy recepcion_extras_read on public.op_recepcion_extras for select to authenticated using(exists(select 1 from public.op_recepciones r where r.id=recepcion_id and (public.is_ops_supervisor() or r.origen_local=public.my_local() or r.destino_local=public.my_local())));
drop policy if exists recepcion_extras_mutate on public.op_recepcion_extras;
create policy recepcion_extras_mutate on public.op_recepcion_extras for all to authenticated using(exists(select 1 from public.op_recepciones r where r.id=recepcion_id and r.estado='en_control' and (public.is_ops_supervisor() or r.destino_local=public.my_local()))) with check(exists(select 1 from public.op_recepciones r where r.id=recepcion_id and r.estado='en_control' and (public.is_ops_supervisor() or r.destino_local=public.my_local())));

drop policy if exists recepcion_participantes_scope on public.op_recepcion_participantes;
create policy recepcion_participantes_scope on public.op_recepcion_participantes for all to authenticated using(exists(select 1 from public.op_recepciones r where r.id=recepcion_id and (public.is_ops_supervisor() or r.origen_local=public.my_local() or r.destino_local=public.my_local()))) with check(usuario_id=auth.uid() and exists(select 1 from public.op_recepciones r where r.id=recepcion_id and (public.is_ops_supervisor() or r.destino_local=public.my_local())));
drop policy if exists recepcion_eventos_scope on public.op_recepcion_eventos;
create policy recepcion_eventos_scope on public.op_recepcion_eventos for all to authenticated using(exists(select 1 from public.op_recepciones r where r.id=recepcion_id and (public.is_ops_supervisor() or r.origen_local=public.my_local() or r.destino_local=public.my_local()))) with check(exists(select 1 from public.op_recepciones r where r.id=recepcion_id and (public.is_ops_supervisor() or r.destino_local=public.my_local())));
drop policy if exists recepcion_pedidos_scope on public.op_recepcion_pedidos;
create policy recepcion_pedidos_scope on public.op_recepcion_pedidos for select to authenticated using(exists(select 1 from public.op_recepciones r where r.id=recepcion_id and (public.is_ops_supervisor() or r.origen_local=public.my_local() or r.destino_local=public.my_local())));

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('op-recepciones','op-recepciones',false,31457280,array['application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/octet-stream'])
on conflict(id) do nothing;
drop policy if exists op_recepciones_storage_read on storage.objects;
create policy op_recepciones_storage_read on storage.objects for select to authenticated using(bucket_id='op-recepciones' and exists(select 1 from public.op_recepciones r where r.id::text=split_part(name,'/',1) and (public.is_ops_supervisor() or r.origen_local=public.my_local() or r.destino_local=public.my_local())));
drop policy if exists op_recepciones_storage_insert on storage.objects;
create policy op_recepciones_storage_insert on storage.objects for insert to authenticated with check(bucket_id='op-recepciones');
drop policy if exists op_recepciones_storage_delete on storage.objects;
create policy op_recepciones_storage_delete on storage.objects for delete to authenticated using(bucket_id='op-recepciones' and (owner_id=auth.uid()::text or public.is_ops_supervisor()));

do $$
declare t text;
begin
  foreach t in array array['op_recepciones','op_recepcion_items','op_recepcion_extras','op_recepcion_participantes','op_recepcion_eventos'] loop
    if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t) then execute format('alter publication supabase_realtime add table public.%I',t); end if;
  end loop;
end $$;

grant execute on function public.op_crear_recepcion(text,text,date,text,text,jsonb,jsonb,text) to authenticated;
grant execute on function public.op_recepcion_cantidad(uuid,text,integer,integer,text,text) to authenticated;
grant execute on function public.op_recepcion_no_recibido(uuid,text,boolean,text,text) to authenticated;
grant execute on function public.op_recepcion_extra(uuid,text,text,text,integer,integer,text,text) to authenticated;
grant execute on function public.op_recepcion_cerrar(uuid,text) to authenticated;
grant execute on function public.op_eliminar_recepcion(uuid) to authenticated;
grant execute on function public.op_marcar_cliente_avisado(uuid) to authenticated;
