-- Motivos operativos, gestion entre locales, edicion y eliminacion auditada.

begin;

alter table public.op_reservas
  add column if not exists pedido_local_gestion text,
  add column if not exists pedido_local_origen text;

alter table public.op_reservas drop constraint if exists op_reservas_pedido_local_gestion_check;
alter table public.op_reservas add constraint op_reservas_pedido_local_gestion_check
  check (pedido_local_gestion is null or pedido_local_gestion in ('crear','existente','externo'));

alter table public.pedidos
  add column if not exists generado_desde_reserva boolean not null default false;

update public.pedidos
set generado_desde_reserva=true
where reserva_id is not null
  and coalesce(notas,'') like 'Creado desde Control de reservas%';

insert into public.op_reserva_motivos(local_nombre,nombre,orden)
select l.nombre,m.nombre,m.orden
from public.locales l
cross join (values
  ('Pedido a otro local',10),
  ('Esperando proveedor',20),
  ('Ya estaba en local',30)
) as m(nombre,orden)
on conflict (local_nombre,lower(nombre)) do update
set activo=true,orden=excluded.orden,updated_at=now();

update public.op_reserva_motivos
set activo=nombre in ('Pedido a otro local','Esperando proveedor','Ya estaba en local'),updated_at=now()
where activo is distinct from (nombre in ('Pedido a otro local','Esperando proveedor','Ya estaba en local'));

-- Normaliza historicos para que Motivo describa de donde sale la mercaderia.
with clasificacion as (
  select r.id,r.local_nombre,
    case
      when bool_or(i.procedencia='pedido_local') then 'Pedido a otro local'
      when bool_and(i.procedencia='local') then 'Ya estaba en local'
      else 'Esperando proveedor'
    end motivo,
    max(i.origen_local) filter(where i.procedencia='pedido_local') origen,
    bool_or(i.pedido_id is not null and coalesce(p.generado_desde_reserva,false)) generado,
    bool_or(i.pedido_id is not null and not coalesce(p.generado_desde_reserva,false)) existente
  from public.op_reservas r
  join public.op_reserva_items i on i.reserva_id=r.id
  left join public.pedidos p on p.id=i.pedido_id
  group by r.id,r.local_nombre
)
update public.op_reservas r
set motivo_id=m.id,motivo_nombre=c.motivo,
  pedido_local_origen=case when c.motivo='Pedido a otro local' then c.origen else null end,
  pedido_local_gestion=case when c.motivo<>'Pedido a otro local' then null when c.generado then 'crear' when c.existente then 'existente' else 'externo' end
from clasificacion c
join public.op_reserva_motivos m on m.local_nombre=c.local_nombre and m.nombre=c.motivo
where r.id=c.id;

create table if not exists public.op_reserva_eliminaciones (
  id bigint generated by default as identity primary key,
  reserva_id uuid not null,
  codigo text not null,
  local_nombre text not null,
  motivo text not null,
  snapshot jsonb not null,
  usuario_id uuid references public.perfiles(id) on delete set null,
  invitado_id uuid references public.op_reserva_invitados(id) on delete set null,
  autor_nombre text not null,
  created_at timestamptz not null default now()
);

create index if not exists op_reserva_eliminaciones_local_fecha_idx
  on public.op_reserva_eliminaciones(local_nombre,created_at desc);

alter table public.op_reserva_eliminaciones enable row level security;
drop policy if exists op_reserva_eliminaciones_read on public.op_reserva_eliminaciones;
create policy op_reserva_eliminaciones_read on public.op_reserva_eliminaciones for select to authenticated
  using(public.is_ops_supervisor() or local_nombre=public.my_local());
grant select on public.op_reserva_eliminaciones to authenticated;

create or replace function public.op_reserva_normalizar_items(p_items jsonb,p_motivo text,p_origen text default null)
returns jsonb language sql immutable security definer set search_path=public,pg_temp as $$
  select coalesce(jsonb_agg(
    x || jsonb_build_object(
      'procedencia',case p_motivo when 'Ya estaba en local' then 'local' when 'Esperando proveedor' then 'proveedor' else 'pedido_local' end,
      'cantidad_local',case when p_motivo='Ya estaba en local' and coalesce(x->>'cantidad','')~'^\d{1,6}$' then (x->>'cantidad')::integer else coalesce(nullif(x->>'cantidad_local','')::integer,0) end,
      'origen_local',case when p_motivo='Pedido a otro local' then nullif(trim(coalesce(p_origen,'')),'') else null end
    ) order by ord
  ),'[]'::jsonb)
  from jsonb_array_elements(coalesce(p_items,'[]'::jsonb)) with ordinality as item(x,ord)
$$;
revoke all on function public.op_reserva_normalizar_items(jsonb,text,text) from public,anon,authenticated;

create or replace function public.op_reserva_pedidos_candidatos(p_local text,p_consulta text default null,p_acceso text default null)
returns jsonb language plpgsql stable security definer set search_path=public,extensions,pg_temp as $$
declare a jsonb; q text; result jsonb;
begin
  a:=public.op_reserva_actor(p_acceso);
  if not (coalesce((a->>'supervisor')::boolean,false) or p_local=a->>'local') then raise exception 'No podés gestionar pedidos para ese local'; end if;
  q:=lower(unaccent(trim(coalesce(p_consulta,''))));
  select coalesce(jsonb_agg(to_jsonb(x) order by x.created_at desc),'[]') into result from (
    select p.id,p.origen_local,p.destino_local,p.cliente,p.telefono,p.estado,p.created_at,
      coalesce(jsonb_agg(jsonb_build_object('codigo',pp.codigo,'nombre',pp.nombre,'cantidad',coalesce(pp.cantidad_aceptada,pp.cantidad)) order by pp.nombre),'[]') productos
    from public.pedidos p join public.pedido_productos pp on pp.pedido_id=p.id
    where p.destino_local=p_local and p.estado<>'denegado' and p.reserva_id is null
      and (q='' or lower(unaccent(concat_ws(' ',p.id::text,p.origen_local,p.cliente,p.telefono,pp.codigo,pp.nombre))) like '%'||q||'%')
    group by p.id order by p.created_at desc limit 40
  ) x;
  return result;
end $$;

create or replace function public.op_reserva_crear_v2(p_datos jsonb,p_acceso text default null)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare m public.op_reserva_motivos; datos jsonb; items jsonb; result jsonb; rid uuid; gestion text; origen text; existente uuid;
begin
  select * into m from public.op_reserva_motivos where id=(p_datos->>'motivo_id')::uuid and activo;
  if m.id is null or m.nombre not in ('Pedido a otro local','Esperando proveedor','Ya estaba en local') then raise exception 'Elegí uno de los tres motivos operativos'; end if;
  gestion:=nullif(trim(coalesce(p_datos->>'pedido_local_gestion','')),'');
  origen:=nullif(trim(coalesce(p_datos->>'pedido_local_origen','')),'');
  if m.nombre='Pedido a otro local' then
    if gestion not in ('crear','existente','externo') then raise exception 'Indicá cómo se gestionará el pedido entre locales'; end if;
    if origen is null or origen=m.local_nombre or not exists(select 1 from public.locales where nombre=origen) then raise exception 'Elegí el local de origen'; end if;
    if gestion='existente' then
      if coalesce(p_datos->>'pedido_existente_id','')!~'^[0-9a-fA-F-]{36}$' then raise exception 'Elegí el pedido existente'; end if;
      existente:=(p_datos->>'pedido_existente_id')::uuid;
    end if;
  else gestion:=null;origen:=null; end if;

  items:=public.op_reserva_normalizar_items(p_datos->'items',m.nombre,origen);
  if m.nombre='Pedido a otro local' and gestion<>'crear' then
    select coalesce(jsonb_agg(x||jsonb_build_object('procedencia','otro') order by ord),'[]'::jsonb) into items
    from jsonb_array_elements(items) with ordinality as item(x,ord);
  end if;
  datos:=p_datos||jsonb_build_object('items',items);
  result:=public.op_reserva_crear(datos,p_acceso);
  rid:=(result->>'id')::uuid;
  update public.op_reservas set pedido_local_gestion=gestion,pedido_local_origen=origen where id=rid;
  if m.nombre='Pedido a otro local' then
    update public.op_reserva_items set procedencia='pedido_local',origen_local=origen where reserva_id=rid;
    if gestion='crear' then
      update public.pedidos set generado_desde_reserva=true where reserva_id=rid;
    elsif gestion='existente' then
      perform public.op_reserva_vincular_pedido(rid,existente,p_acceso);
    end if;
  end if;
  perform public.op_reserva_recalcular(rid,coalesce((public.op_reserva_actor(p_acceso))->>'name','Sistema'));
  return result;
end $$;

create or replace function public.op_reserva_editar(p_reserva uuid,p_datos jsonb,p_acceso text default null)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare a jsonb; r public.op_reservas; l public.locales; m public.op_reserva_motivos; c public.clientes_agenda; origen public.locales;
  datos_items jsonb; gestion text; origen_nombre text; existente uuid; v_phone text; antes jsonb; p_id uuid;
begin
  a:=public.op_reserva_actor(p_acceso);
  select * into r from public.op_reservas where id=p_reserva for update;
  if r.id is null or not public.op_reserva_puede_ver(r.id,a) then raise exception 'Reserva no disponible'; end if;
  if r.estado in ('completado','cancelado') then raise exception 'Una reserva cerrada no se puede editar'; end if;
  if exists(select 1 from public.op_reserva_items where reserva_id=r.id and cantidad_entregada>0) then raise exception 'No se pueden cambiar los datos o productos después de registrar entregas'; end if;
  if exists(select 1 from public.pedidos where reserva_id=r.id and estado<>'pendiente') then raise exception 'El pedido entre locales ya avanzó; corregí el proceso desde su módulo'; end if;
  select * into l from public.locales where nombre=coalesce(nullif(trim(p_datos->>'local'),''),r.local_nombre);
  if l.id is null or l.nombre<>r.local_nombre then raise exception 'No se puede mover una reserva a otro local'; end if;
  select * into m from public.op_reserva_motivos where id=(p_datos->>'motivo_id')::uuid and local_nombre=l.nombre and activo;
  if m.id is null or m.nombre not in ('Pedido a otro local','Esperando proveedor','Ya estaba en local') then raise exception 'Elegí uno de los tres motivos operativos'; end if;
  if char_length(trim(coalesce(p_datos->>'responsable',''))) not between 2 and 80 then raise exception 'El responsable es obligatorio'; end if;
  if jsonb_typeof(p_datos->'items')<>'array' or jsonb_array_length(p_datos->'items') not between 1 and 100 then raise exception 'Agregá al menos un producto'; end if;
  if exists(select 1 from jsonb_array_elements(p_datos->'items') i where nullif(trim(i->>'codigo'),'') is null or nullif(trim(i->>'nombre'),'') is null
    or coalesce(i->>'cantidad','')!~'^\d{1,6}$' or (i->>'cantidad')::integer<1
    or coalesce(i->>'cantidad_local','0')!~'^\d{1,6}$' or (i->>'cantidad_local')::integer>(i->>'cantidad')::integer) then raise exception 'Revisá los productos y cantidades'; end if;

  gestion:=nullif(trim(coalesce(p_datos->>'pedido_local_gestion','')),'');
  origen_nombre:=nullif(trim(coalesce(p_datos->>'pedido_local_origen','')),'');
  if m.nombre='Pedido a otro local' then
    if gestion not in ('crear','existente','externo') then raise exception 'Indicá cómo se gestionará el pedido entre locales'; end if;
    select * into origen from public.locales where nombre=origen_nombre and nombre<>l.nombre;
    if origen.id is null then raise exception 'Elegí el local de origen'; end if;
    if gestion='existente' then
      if coalesce(p_datos->>'pedido_existente_id','')!~'^[0-9a-fA-F-]{36}$' then raise exception 'Elegí el pedido existente'; end if;
      existente:=(p_datos->>'pedido_existente_id')::uuid;
    end if;
  else gestion:=null;origen_nombre:=null; end if;
  datos_items:=public.op_reserva_normalizar_items(p_datos->'items',m.nombre,origen_nombre);
  antes:=jsonb_build_object('reserva',to_jsonb(r)-'qr_token'-'qr_token_hash','items',(select coalesce(jsonb_agg(to_jsonb(i) order by i.created_at),'[]') from public.op_reserva_items i where i.reserva_id=r.id));

  v_phone:=regexp_replace(coalesce(p_datos#>>'{cliente,telefono}',''),'\D','','g');
  if v_phone<>'' then perform pg_advisory_xact_lock(hashtext('agenda:'||v_phone)); end if;
  if nullif(p_datos#>>'{cliente,id}','') is not null then
    select * into c from public.clientes_agenda where id=(p_datos#>>'{cliente,id}')::uuid;
  elsif v_phone<>'' then
    select * into c from public.clientes_agenda where regexp_replace(coalesce(telefono,''),'\D','','g')=v_phone order by updated_at desc limit 1;
  end if;
  if c.id is null and nullif(trim(concat_ws('',p_datos#>>'{cliente,nombre}',p_datos#>>'{cliente,apellido}',p_datos#>>'{cliente,telefono}',p_datos#>>'{cliente,direccion}',p_datos#>>'{cliente,documento}')),'') is not null then
    insert into public.clientes_agenda(nombre,apellido,telefono,direccion,documento)
    values(nullif(left(trim(coalesce(p_datos#>>'{cliente,nombre}','')),120),''),nullif(left(trim(coalesce(p_datos#>>'{cliente,apellido}','')),120),''),
      nullif(left(trim(coalesce(p_datos#>>'{cliente,telefono}','')),40),''),nullif(left(trim(coalesce(p_datos#>>'{cliente,direccion}','')),240),''),
      nullif(left(trim(coalesce(p_datos#>>'{cliente,documento}','')),50),'')) returning * into c;
  elsif c.id is not null then
    update public.clientes_agenda set nombre=coalesce(nullif(trim(p_datos#>>'{cliente,nombre}'),''),nombre),apellido=coalesce(nullif(trim(p_datos#>>'{cliente,apellido}'),''),apellido),
      telefono=coalesce(nullif(trim(p_datos#>>'{cliente,telefono}'),''),telefono),direccion=coalesce(nullif(trim(p_datos#>>'{cliente,direccion}'),''),direccion),
      documento=coalesce(nullif(trim(p_datos#>>'{cliente,documento}'),''),documento),updated_at=now() where id=c.id returning * into c;
  end if;

  delete from public.pedidos where reserva_id=r.id and generado_desde_reserva and estado='pendiente';
  update public.pedidos set reserva_id=null,updated_at=now() where reserva_id=r.id;
  delete from public.op_reserva_items where reserva_id=r.id;
  update public.op_reservas set motivo_id=m.id,motivo_nombre=m.nombre,motivo_comentario=nullif(left(trim(coalesce(p_datos->>'motivo_comentario','')),1000),''),
    responsable_nombre=left(trim(p_datos->>'responsable'),80),cliente_id=c.id,
    cliente_nombre=coalesce(c.nombre,nullif(left(trim(coalesce(p_datos#>>'{cliente,nombre}','')),120),'')),cliente_apellido=coalesce(c.apellido,nullif(left(trim(coalesce(p_datos#>>'{cliente,apellido}','')),120),'')),
    cliente_telefono=coalesce(c.telefono,nullif(left(trim(coalesce(p_datos#>>'{cliente,telefono}','')),40),'')),cliente_direccion=coalesce(c.direccion,nullif(left(trim(coalesce(p_datos#>>'{cliente,direccion}','')),240),'')),
    cliente_documento=coalesce(c.documento,nullif(left(trim(coalesce(p_datos#>>'{cliente,documento}','')),50),'')),referencia_externa=nullif(left(trim(coalesce(p_datos->>'referencia_externa','')),120),''),
    remito_numero=nullif(left(trim(coalesce(p_datos->>'remito_numero','')),100),''),fecha_estimada=case when coalesce(p_datos->>'fecha_estimada','')~'^\d{4}-\d{2}-\d{2}$' then (p_datos->>'fecha_estimada')::date else null end,
    pedido_local_gestion=gestion,pedido_local_origen=origen_nombre,estado='buscando',estado_antes_vencido=null,updated_at=now() where id=r.id;
  insert into public.op_reserva_items(reserva_id,codigo,nombre,cantidad,cantidad_local,procedencia,origen_local,fecha_estimada,remito_numero,comentario,estado)
  select r.id,left(trim(x->>'codigo'),80),left(trim(x->>'nombre'),240),(x->>'cantidad')::integer,coalesce((x->>'cantidad_local')::integer,0),x->>'procedencia',
    nullif(left(trim(coalesce(x->>'origen_local','')),120),''),case when coalesce(x->>'fecha_estimada','')~'^\d{4}-\d{2}-\d{2}$' then (x->>'fecha_estimada')::date else null end,
    nullif(left(trim(coalesce(x->>'remito_numero','')),100),''),nullif(left(trim(coalesce(x->>'comentario','')),500),''),
    case when coalesce((x->>'cantidad_local')::integer,0)>0 then 'separado' else 'pendiente' end
  from jsonb_array_elements(datos_items) x;
  if not exists(select 1 from public.op_reserva_items where reserva_id=r.id and cantidad_local>0) then
    update public.op_reservas set mercaderia_local_at=null,vencimiento_at=null,excepcion_hasta=null,excepcion_motivo=null where id=r.id;
  end if;

  if m.nombre='Pedido a otro local' and gestion='crear' then
    insert into public.pedidos(origen_local,origen_almacen,destino_local,destino_almacen,cliente,telefono,notas,estado,creado_por,canal_creacion,reserva_id,generado_desde_reserva)
    values(origen.nombre,origen.almacen,l.nombre,l.almacen,nullif(trim(concat_ws(' ',coalesce(c.nombre,p_datos#>>'{cliente,nombre}'),coalesce(c.apellido,p_datos#>>'{cliente,apellido}'))),''),
      coalesce(c.telefono,nullif(trim(p_datos#>>'{cliente,telefono}'),'')),'Creado desde Control de reservas · Reserva #'||r.codigo||case when nullif(trim(coalesce(p_datos->>'motivo_comentario','')),'') is not null then ' · '||trim(p_datos->>'motivo_comentario') else '' end,
      'pendiente',(a->>'user_id')::uuid,'interno',r.id,true) returning id into p_id;
    insert into public.pedido_productos(pedido_id,codigo,nombre,cantidad)
      select p_id,codigo,max(nombre),sum(cantidad)::integer from public.op_reserva_items where reserva_id=r.id group by codigo;
    update public.op_reserva_items set pedido_id=p_id where reserva_id=r.id;
    insert into public.pedido_historial(pedido_id,estado,usuario_id,persona_nombre) values(p_id,'pendiente',(a->>'user_id')::uuid,a->>'name');
    insert into public.notificaciones(usuario_id,titulo,cuerpo,pedido_id)
      select p.id,'Nuevo pedido vinculado a una reserva','#'||r.codigo||' · '||l.nombre,p_id from public.perfiles p where p.approved=true and p.local_nombre=origen.nombre;
  elsif m.nombre='Pedido a otro local' and gestion='existente' then
    perform public.op_reserva_vincular_pedido(r.id,existente,p_acceso);
  end if;
  perform public.op_reserva_recalcular(r.id,a->>'name');
  insert into public.op_reserva_eventos(reserva_id,accion,estado,detalle,usuario_id,invitado_id,autor_nombre)
    values(r.id,'editar',null,jsonb_build_object('antes',antes,'motivo',m.nombre,'gestion',gestion),(a->>'user_id')::uuid,(a->>'guest_id')::uuid,a->>'name');
  return public.op_reserva_detalle(r.id,p_acceso);
end $$;

create or replace function public.op_reserva_eliminar(p_reserva uuid,p_codigo text,p_motivo text,p_acceso text default null)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare a jsonb; r public.op_reservas; snap jsonb;
begin
  a:=public.op_reserva_actor(p_acceso);
  select * into r from public.op_reservas where id=p_reserva for update;
  if r.id is null or not public.op_reserva_puede_ver(r.id,a) then raise exception 'Reserva no disponible'; end if;
  if upper(trim(coalesce(p_codigo,'')))<>upper(r.codigo) then raise exception 'Escribí el código de la reserva para confirmar'; end if;
  if char_length(trim(coalesce(p_motivo,''))) not between 3 and 500 then raise exception 'Explicá por qué se elimina'; end if;
  if exists(select 1 from public.op_reserva_items where reserva_id=r.id and cantidad_entregada>0) then raise exception 'Una reserva con entregas no se puede eliminar; cancelala para conservar la trazabilidad'; end if;
  if exists(select 1 from public.pedidos where reserva_id=r.id and generado_desde_reserva and estado<>'pendiente') then raise exception 'El pedido entre locales ya avanzó y no se puede eliminar desde Reservas'; end if;
  snap:=jsonb_build_object('reservation',to_jsonb(r)-'qr_token'-'qr_token_hash',
    'items',(select coalesce(jsonb_agg(to_jsonb(i) order by i.created_at),'[]') from public.op_reserva_items i where i.reserva_id=r.id),
    'comments',(select coalesce(jsonb_agg(to_jsonb(c) order by c.created_at),'[]') from public.op_reserva_comentarios c where c.reserva_id=r.id),
    'events',(select coalesce(jsonb_agg(to_jsonb(e) order by e.created_at),'[]') from public.op_reserva_eventos e where e.reserva_id=r.id),
    'delete_reason',trim(p_motivo));
  insert into public.op_reserva_eliminaciones(reserva_id,codigo,local_nombre,motivo,snapshot,usuario_id,invitado_id,autor_nombre)
    values(r.id,r.codigo,r.local_nombre,trim(p_motivo),snap,(a->>'user_id')::uuid,(a->>'guest_id')::uuid,a->>'name');
  delete from public.pedidos where reserva_id=r.id and generado_desde_reserva and estado='pendiente';
  delete from public.op_reservas where id=r.id;
  return jsonb_build_object('ok',true,'id',r.id,'code',r.codigo);
end $$;

revoke all on function public.op_reserva_pedidos_candidatos(text,text,text) from public;
revoke all on function public.op_reserva_crear_v2(jsonb,text) from public;
revoke all on function public.op_reserva_editar(uuid,jsonb,text) from public;
revoke all on function public.op_reserva_eliminar(uuid,text,text,text) from public;
grant execute on function public.op_reserva_pedidos_candidatos(text,text,text) to anon,authenticated;
grant execute on function public.op_reserva_crear_v2(jsonb,text) to anon,authenticated;
grant execute on function public.op_reserva_editar(uuid,jsonb,text) to anon,authenticated;
grant execute on function public.op_reserva_eliminar(uuid,text,text,text) to anon,authenticated;

commit;
