(async function(){
  'use strict';
  const $=id=>document.getElementById(id),E=window.ReservaEngine,cfg=window.SUCANEITOR_CLOUD_CONFIG;
  const db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey);
  const html=v=>String(v==null?'':v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const fmt=v=>v?new Date(v).toLocaleString('es-UY',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—';
  const itemOrigin=i=>i.procedencia==='proveedor'?`Esperando proveedor${i.proveedor_nombre?' · '+i.proveedor_nombre:''}`:i.procedencia==='pedido_local'?`Pedido a otro local${i.origen_local?' · Desde '+i.origen_local:''}${i.pedido_local_gestion==='crear'?' · Pedido creado':i.pedido_local_gestion==='existente'?' · Pedido vinculado':i.pedido_local_gestion==='externo'?' · Coordinado fuera del sistema':''}`:(E.sources[i.procedencia]||i.procedencia);
  const token=decodeURIComponent(location.hash.slice(1)).trim();
  const trackingUrl=()=>`${location.origin}/reserva#${encodeURIComponent(token)}`;
  const qrDataUrl=text=>new Promise((resolve,reject)=>{const box=document.createElement('div');box.style.cssText='position:fixed;left:-10000px;top:0;background:#fff;padding:0';document.body.appendChild(box);new QRCode(box,{text,width:232,height:232,colorDark:'#000000',colorLight:'#ffffff',correctLevel:QRCode.CorrectLevel.M});setTimeout(()=>{const canvas=box.querySelector('canvas'),img=box.querySelector('img'),url=canvas?.toDataURL('image/png')||img?.src;box.remove();url?resolve(url):reject(new Error('No se pudo generar el QR'));},80);});
  async function printLabel(r){const win=window.open('','_blank','width=1000,height=560');if(!win)return alert('Permití las ventanas emergentes para imprimir.');win.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Preparando etiqueta…</title></head><body style="font-family:Arial,sans-serif;padding:24px">Preparando etiqueta…</body></html>');win.document.close();try{const qr=await qrDataUrl(trackingUrl()),number=r.number??r.code,customer=r.customer||'Sin cliente',phone=r.phone||'SIN TELÉFONO',date=new Date(r.created_at).toLocaleDateString('es-UY'),warehouse=r.warehouse||r.local||'',locationText=r.location;win.document.open();win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Reserva ${html(number)}</title><style>@page{size:80mm 200mm;margin:0}*{box-sizing:border-box}html{width:80mm;height:200mm;margin:0;padding:0;overflow:hidden;color:#000;background:#fff;font-family:Arial,sans-serif}body{position:relative;width:80mm;height:200mm;margin:0;padding:0;overflow:hidden}.label{position:absolute;top:0;left:79.5mm;width:199mm;height:79mm;margin:0;padding:5mm 8mm;overflow:hidden;transform:rotate(90deg);transform-origin:top left;break-inside:avoid;page-break-inside:avoid;display:grid;grid-template-columns:66mm minmax(0,1fr);gap:9mm;align-items:center}.qr{display:block;width:66mm;height:66mm;image-rendering:pixelated}.copy{min-width:0;border-left:.5mm solid #000;padding-left:8mm}.code{font:800 17pt monospace;letter-spacing:.4mm}.name{margin:4mm 0 2.5mm;font-size:29pt;font-weight:900;line-height:1.02;word-break:break-word}.phone{font-size:17pt;font-weight:800;line-height:1.15}.date{margin-top:3mm;font-size:13pt;font-weight:700}.location{margin-top:2mm;font-size:11pt;font-weight:800;line-height:1.15}.instruction{margin-top:2.5mm;font-size:9pt;font-weight:800;letter-spacing:.25mm}.brand{margin-top:1.5mm;font-size:9pt;font-weight:800}@media print{html,body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}</style></head><body><div class="label"><img class="qr" src="${qr}" alt="QR de la reserva"><div class="copy"><div class="code">RESERVA #${html(number)}</div><div class="name">${html(customer)}</div><div class="phone">TEL: ${html(phone)}</div><div class="date">${html(date)} · LOCAL ${html(warehouse)}</div>${locationText?`<div class="location">UBICACIÓN: ${html(locationText)}</div>`:''}<div class="instruction">ESCANEÁ EL QR PARA VER PRODUCTOS Y SEGUIMIENTO</div><div class="brand">SUCAN · CONTROL DE RESERVAS</div></div></div><script>onload=()=>{setTimeout(()=>print(),120);onafterprint=()=>close()}<\/script></body></html>`);win.document.close();}catch(error){if(!win.closed)win.close();alert(error.message||'No se pudo preparar la etiqueta.');}}
  try{
    if(!/^[a-f0-9]{48,128}$/i.test(token))throw new Error('El enlace no contiene un QR válido.');
    const {data,error}=await db.rpc('op_reserva_qr_detalle',{p_token:token});if(error)throw error;if(!data?.ok)throw new Error(data?.error||'No encontramos la reserva.');
    const r=data.reservation,d=E.deadlineInfo(r.expires_at),number=r.number??r.code;$('lookup-code').textContent=`RESERVA #${number} · ${r.local}`;$('lookup-customer').textContent=r.customer||'Sin cliente';$('lookup-reason').textContent=`${r.reason} · Responsable: ${r.responsible}`;$('lookup-state').textContent=E.labels[r.state]||r.state;$('lookup-state').className=`status ${r.state}`;
    $('lookup-data').innerHTML=`<div class="row"><span>Teléfono</span><strong>${html(r.phone||'—')}</strong></div><div class="row"><span>Ubicación en tienda</span><strong>${html(r.location||'Consultar al responsable')}</strong></div><div class="row"><span>Creada</span><strong>${fmt(r.created_at)}</strong></div><div class="row"><span>Mercadería desde</span><strong>${fmt(r.merchandise_at)}</strong></div><div class="row"><span>Plazo</span><strong>${html(d.label)}</strong></div><div class="row"><span>Referencia</span><strong>${html(r.reference||'—')}</strong></div>`;
    $('lookup-products').innerHTML=(r.items||[]).map(i=>`<div class="product"><strong>${html(i.nombre)} · ${i.cantidad}</strong><small>${html(i.codigo)} · ${html(itemOrigin(i))} · ${i.cantidad_local} en local · ${i.cantidad_entregada} entregadas${i.fecha_estimada?' · Estimado '+html(i.fecha_estimada):''}${i.remito_numero?' · Remito '+html(i.remito_numero):''}</small></div>`).join('')||'<p>Sin productos.</p>';
    if(r.state==='vencido'){$('lookup-alert').hidden=false;$('lookup-alert').textContent='Esta mercadería superó el plazo de reserva. Consultá al responsable antes de entregarla.';}
    $('lookup-print').addEventListener('click',()=>printLabel(r));const {data:{session}}=await db.auth.getSession();$('lookup-manage').href=session?`/reservas?qr=${encodeURIComponent(token)}`:'/?module=reservas';$('lookup-manage').textContent=session?'Abrir reserva':'Iniciar sesión';$('lookup-loading').hidden=true;$('lookup-content').hidden=false;
  }catch(error){$('lookup-loading').hidden=true;$('lookup-error').hidden=false;$('lookup-error-message').textContent=error.message||'No encontramos esta reserva.';}
})();
